name: flutter_mcp_ui_generator
description: JSON generation tools for Flutter MCP UI Renderer. Create UI definitions programmatically with templates and fluent API.
version: 0.2.3
homepage: https://app-appplayer.github.io/makemind
repository: https://github.com/app-appplayer/flutter_mcp_ui_generator
documentation: https://pub.dev/documentation/flutter_mcp_ui_generator/latest/
license: Apache-2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mcp_ui_core: ^0.2.3
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0

flutter:

# Example application
example:
  platforms:
    - android
    - ios
    - web
    - macos
    - linux
    - windows

topics:
  - ui
  - json
  - mcp
  - flutter
  - generator
