// GENERATED by tools/spec_codegen/bin/generator_codegen.dart.
// Do not edit by hand. Re-run the codegen to update.

// One static builder per spec widget yaml. Mirrors the spec
// vocabulary 1:1 so a coverage gap between spec and the
// generator package becomes a codegen build error rather
// than a silent drift.

class MCPUIWidgetBuilders {
  MCPUIWidgetBuilders._();

  /// Wraps a child with accessibility annotations (ARIA-style). See [`13_Accessibility.md`](13_Accessibility.md) for the full property set.
  static Map<String, dynamic> accessibleWrapper({
    required dynamic child,
    dynamic accessibility,
  }) {
    return <String, dynamic>{
      'type': 'accessibleWrapper',
      'child': child,
      if (accessibility != null) 'accessibility': accessibility,
    };
  }

  /// Modal alert with an optional title, an optional body (string or widget),
  /// and a list of labeled action buttons. Dispatched via the `dialog` action
  /// (`{ "type": "dialog", "dialog": { "type": "alertDialog", ... } }`). The
  /// runtime renders it as a `Dialog` surface scoped to the current navigator
  /// (not the root navigator), so tapping an action pops only the dialog.
  static Map<String, dynamic> alertDialog({
    String? title,
    dynamic content,
    bool? dismissible,
    dynamic onClose,
    dynamic actions,
  }) {
    return <String, dynamic>{
      'type': 'alertDialog',
      if (title != null) 'title': title,
      if (content != null) 'content': content,
      if (dismissible != null) 'dismissible': dismissible,
      if (onClose != null) 'onClose': onClose,
      if (actions != null) 'actions': actions,
    };
  }

  /// Aligns a single child at a specified alignment.
  static Map<String, dynamic> align({
    dynamic alignment,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'align',
      if (alignment != null) 'alignment': alignment,
      'child': child,
    };
  }

  /// Implicitly animates a child's `alignment` within its bounds. Use
  /// for slide-from-edge / settle-to-position micro-interactions.
  static Map<String, dynamic> animatedAlign({
    required dynamic alignment,
    dynamic duration,
    dynamic curve,
    dynamic onEnd,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'animatedAlign',
      'alignment': alignment,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      if (onEnd != null) 'onEnd': onEnd,
      'child': child,
    };
  }

  /// Container that implicitly animates property changes. Whenever any
  /// of the size/decoration/alignment/padding fields change between
  /// builds the runtime tweens between the old and new values over
  /// `duration` using `curve`.
  static Map<String, dynamic> animatedContainer({
    dynamic duration,
    dynamic curve,
    dynamic width,
    dynamic height,
    dynamic padding,
    dynamic margin,
    dynamic alignment,
    dynamic decoration,
    dynamic onEnd,
    dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'animatedContainer',
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (padding != null) 'padding': padding,
      if (margin != null) 'margin': margin,
      if (alignment != null) 'alignment': alignment,
      if (decoration != null) 'decoration': decoration,
      if (onEnd != null) 'onEnd': onEnd,
      if (child != null) 'child': child,
    };
  }

  /// Implicitly animates the default `TextStyle` applied to descendant
  /// `text` / `richText` widgets. Each style field (color, fontSize,
  /// fontWeight, letterSpacing, lineHeight, …) tweens independently.
  /// Use for emphasis transitions (e.g., headline grows + bolds when
  /// selected).
  static Map<String, dynamic> animatedDefaultTextStyle({
    required dynamic style,
    dynamic duration,
    dynamic curve,
    dynamic onEnd,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'animatedDefaultTextStyle',
      'style': style,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      if (onEnd != null) 'onEnd': onEnd,
      'child': child,
    };
  }

  /// Implicitly animates the child's `opacity` whenever it changes.
  /// Use for fade-in / fade-out micro-interactions without explicit
  /// animation controllers.
  static Map<String, dynamic> animatedOpacity({
    required num opacity,
    dynamic duration,
    dynamic curve,
    dynamic onEnd,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'animatedOpacity',
      'opacity': opacity,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      if (onEnd != null) 'onEnd': onEnd,
      'child': child,
    };
  }

  /// Implicitly animates a child's edge offsets inside a `stack`. Same
  /// contract as `positioned` (top/right/bottom/left/width/height) but
  /// changes are tweened. Only valid as a `stack` child.
  static Map<String, dynamic> animatedPositioned({
    dynamic top,
    dynamic right,
    dynamic bottom,
    dynamic left,
    dynamic width,
    dynamic height,
    dynamic duration,
    dynamic curve,
    dynamic onEnd,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'animatedPositioned',
      if (top != null) 'top': top,
      if (right != null) 'right': right,
      if (bottom != null) 'bottom': bottom,
      if (left != null) 'left': left,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      if (onEnd != null) 'onEnd': onEnd,
      'child': child,
    };
  }

  /// Sizes the child to a specific aspect ratio.
  static Map<String, dynamic> aspectRatio({
    num? aspectRatio,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'aspectRatio',
      if (aspectRatio != null) 'aspectRatio': aspectRatio,
      'child': child,
    };
  }

  /// Circular widget for user images or initials.
  static Map<String, dynamic> avatar({
    String? src,
    String? label,
    num? size,
    String? color,
  }) {
    return <String, dynamic>{
      'type': 'avatar',
      if (src != null) 'src': src,
      if (label != null) 'label': label,
      if (size != null) 'size': size,
      if (color != null) 'color': color,
    };
  }

  /// Small status indicator typically anchored to another widget.
  static Map<String, dynamic> badge({
    String? label,
    String? color,
    dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'badge',
      if (label != null) 'label': label,
      if (color != null) 'color': color,
      if (child != null) 'child': child,
    };
  }

  /// Persistent message banner at the top of a section or page.
  static Map<String, dynamic> banner({
    required String message,
    String? severity,
    dynamic actions,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'banner',
      'message': message,
      if (severity != null) 'severity': severity,
      if (actions != null) 'actions': actions,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Aligns a child by its baseline.
  static Map<String, dynamic> baseline({
    required num baseline,
    String? baselineType,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'baseline',
      'baseline': baseline,
      if (baselineType != null) 'baselineType': baselineType,
      'child': child,
    };
  }

  /// Bottom navigation bar. Each item's text field is `label`.
  static Map<String, dynamic> bottomNavigation({
    dynamic selectedIndex,
    required dynamic items,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'bottomNavigation',
      if (selectedIndex != null) 'selectedIndex': selectedIndex,
      'items': items,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Modal bottom sheet with swipeable handle.
  static Map<String, dynamic> bottomSheet({
    required dynamic child,
    bool? isDismissible,
    bool? enableDrag,
    String? backgroundColor,
    dynamic shape,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'bottomSheet',
      'child': child,
      if (isDismissible != null) 'isDismissible': isDismissible,
      if (enableDrag != null) 'enableDrag': enableDrag,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (shape != null) 'shape': shape,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Generic single-child container that applies size, padding, margin, and a
  /// decoration (background color, border, shadow, gradient, borderRadius). Most
  /// commonly used as a styled wrapper around any child widget.
  static Map<String, dynamic> box({
    num? width,
    num? height,
    num? minWidth,
    num? maxWidth,
    num? minHeight,
    num? maxHeight,
    String? padding,
    dynamic margin,
    dynamic alignment,
    dynamic color,
    dynamic decoration,
  }) {
    return <String, dynamic>{
      'type': 'box',
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (minWidth != null) 'minWidth': minWidth,
      if (maxWidth != null) 'maxWidth': maxWidth,
      if (minHeight != null) 'minHeight': minHeight,
      if (maxHeight != null) 'maxHeight': maxHeight,
      if (padding != null) 'padding': padding,
      if (margin != null) 'margin': margin,
      if (alignment != null) 'alignment': alignment,
      if (color != null) 'color': color,
      if (decoration != null) 'decoration': decoration,
    };
  }

  /// Interactive button. The canonical label field is `label`.
  static Map<String, dynamic> button({
    required String label,
    String? variant,
    String? elevation,
    String? icon,
    bool? enabled,
    dynamic onTap,
    dynamic onDoubleTap,
    dynamic onLongPress,
  }) {
    return <String, dynamic>{
      'type': 'button',
      'label': label,
      if (variant != null) 'variant': variant,
      if (elevation != null) 'elevation': elevation,
      if (icon != null) 'icon': icon,
      if (enabled != null) 'enabled': enabled,
      if (onTap != null) 'onTap': onTap,
      if (onDoubleTap != null) 'onDoubleTap': onDoubleTap,
      if (onLongPress != null) 'onLongPress': onLongPress,
    };
  }

  /// Calendar view for date selection and event display.
  static Map<String, dynamic> calendar({
    dynamic selectedDate,
    dynamic events,
    String? firstDate,
    String? lastDate,
    String? view,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'calendar',
      if (selectedDate != null) 'selectedDate': selectedDate,
      if (events != null) 'events': events,
      if (firstDate != null) 'firstDate': firstDate,
      if (lastDate != null) 'lastDate': lastDate,
      if (view != null) 'view': view,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// General-purpose vector drawing via an ordered command array. All numeric and color properties support binding expressions, enabling data-driven graphics (progress rings, custom indicators, composable chart primitives).
  static Map<String, dynamic> canvas() {
    return <String, dynamic>{
      'type': 'canvas',
    };
  }

  /// Elevated single-child container.
  static Map<String, dynamic> card({
    String? elevation,
    dynamic margin,
    String? shape,
    dynamic color,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'card',
      if (elevation != null) 'elevation': elevation,
      if (margin != null) 'margin': margin,
      if (shape != null) 'shape': shape,
      if (color != null) 'color': color,
      'child': child,
    };
  }

  /// Horizontally scrolling browser with optional partial-viewport
  /// framing (cover-flow / album-shelf style). Distinct from `pageView`
  /// (which always snaps a full viewport per page) — `carousel` lets
  /// authors set `viewportFraction` < 1 so adjacent items peek in,
  /// signalling "more to scroll". Used for content shelves (book
  /// covers, album browsers, magazine front pages).
  static Map<String, dynamic> carousel({
    dynamic items,
    dynamic itemTemplate,
    dynamic children,
    String? scrollDirection,
    num? viewportFraction,
    bool? loop,
    num? autoPlay,
    num? initialIndex,
    String? transition,
    String? indicatorPosition,
    dynamic onPageChanged,
  }) {
    return <String, dynamic>{
      'type': 'carousel',
      if (items != null) 'items': items,
      if (itemTemplate != null) 'itemTemplate': itemTemplate,
      if (children != null) 'children': children,
      if (scrollDirection != null) 'scrollDirection': scrollDirection,
      if (viewportFraction != null) 'viewportFraction': viewportFraction,
      if (loop != null) 'loop': loop,
      if (autoPlay != null) 'autoPlay': autoPlay,
      if (initialIndex != null) 'initialIndex': initialIndex,
      if (transition != null) 'transition': transition,
      if (indicatorPosition != null) 'indicatorPosition': indicatorPosition,
      if (onPageChanged != null) 'onPageChanged': onPageChanged,
    };
  }

  /// Centers a single child within available space.
  static Map<String, dynamic> center({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'center',
      'child': child,
    };
  }

  /// Data visualization widget with multiple chart types.
  static Map<String, dynamic> chart({
    required String chartType,
    required dynamic data,
    String? data_datasets___label,
    required dynamic data_datasets___data,
    String? data_datasets___borderColor,
    String? data_datasets___backgroundColor,
    dynamic options,
    bool? options_responsive,
    num? options_animation_duration,
    String? options_legend_position,
    num? width,
    num? height,
  }) {
    return <String, dynamic>{
      'type': 'chart',
      'chartType': chartType,
      'data': data,
      if (data_datasets___label != null) 'data.datasets[].label': data_datasets___label,
      'data.datasets[].data': data_datasets___data,
      if (data_datasets___borderColor != null) 'data.datasets[].borderColor': data_datasets___borderColor,
      if (data_datasets___backgroundColor != null) 'data.datasets[].backgroundColor': data_datasets___backgroundColor,
      if (options != null) 'options': options,
      if (options_responsive != null) 'options.responsive': options_responsive,
      if (options_animation_duration != null) 'options.animation.duration': options_animation_duration,
      if (options_legend_position != null) 'options.legend.position': options_legend_position,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
    };
  }

  /// Boolean checkbox. Shared rows per §2.6.0; `value` is `boolean`.
  static Map<String, dynamic> checkbox({
    String? label,
  }) {
    return <String, dynamic>{
      'type': 'checkbox',
      if (label != null) 'label': label,
    };
  }

  /// Multi-selection checkbox group. Shared rows per §2.6.0; `binding` holds an `array` of selected values (top-level, not per-option).
  static Map<String, dynamic> checkboxGroup({
    required dynamic options,
    String? orientation,
  }) {
    return <String, dynamic>{
      'type': 'checkboxGroup',
      'options': options,
      if (orientation != null) 'orientation': orientation,
    };
  }

  /// Compact element representing an attribute, action, or filter.
  static Map<String, dynamic> chip({
    required String label,
    dynamic avatar,
    bool? selected,
    String? variant,
    dynamic onDelete,
    dynamic onTap,
  }) {
    return <String, dynamic>{
      'type': 'chip',
      'label': label,
      if (avatar != null) 'avatar': avatar,
      if (selected != null) 'selected': selected,
      if (variant != null) 'variant': variant,
      if (onDelete != null) 'onDelete': onDelete,
      if (onTap != null) 'onTap': onTap,
    };
  }

  /// Clips a child to an oval.
  static Map<String, dynamic> clipOval({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'clipOval',
      'child': child,
    };
  }

  /// Clips a child to a rounded rectangle.
  static Map<String, dynamic> clipRRect({
    dynamic borderRadius,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'clipRRect',
      if (borderRadius != null) 'borderRadius': borderRadius,
      'child': child,
    };
  }

  /// Syntax-highlighted code editor.
  static Map<String, dynamic> codeEditor({
    required dynamic code,
    String? language,
    String? theme,
    bool? readOnly,
    bool? showLineNumbers,
    num? fontSize,
    num? lineHeight,
    num? tabSize,
    num? width,
    num? height,
    String? backgroundColor,
    String? textColor,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'codeEditor',
      'code': code,
      if (language != null) 'language': language,
      if (theme != null) 'theme': theme,
      if (readOnly != null) 'readOnly': readOnly,
      if (showLineNumbers != null) 'showLineNumbers': showLineNumbers,
      if (fontSize != null) 'fontSize': fontSize,
      if (lineHeight != null) 'lineHeight': lineHeight,
      if (tabSize != null) 'tabSize': tabSize,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (textColor != null) 'textColor': textColor,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Color selection. Shared rows per §2.6.0; `value` is a hex color string.
  static Map<String, dynamic> colorPicker({
    bool? showAlpha,
    bool? showLabel,
    String? pickerType,
    bool? enableHistory,
  }) {
    return <String, dynamic>{
      'type': 'colorPicker',
      if (showAlpha != null) 'showAlpha': showAlpha,
      if (showLabel != null) 'showLabel': showLabel,
      if (pickerType != null) 'pickerType': pickerType,
      if (enableHistory != null) 'enableHistory': enableHistory,
    };
  }

  /// Renders different branches based on an expression. Two forms are supported: then/else and multi-branch (`switch`/`cases`).
  static Map<String, dynamic> conditional({
    dynamic condition,
    dynamic then,
    dynamic else_,
    dynamic switch_,
    dynamic cases,
    dynamic default_,
  }) {
    return <String, dynamic>{
      'type': 'conditional',
      if (condition != null) 'condition': condition,
      if (then != null) 'then': then,
      if (else_ != null) 'else': else_,
      if (switch_ != null) 'switch': switch_,
      if (cases != null) 'cases': cases,
      if (default_ != null) 'default': default_,
    };
  }

  /// Dialog with arbitrary widget content.
  static Map<String, dynamic> customDialog({
    required dynamic child,
    bool? dismissible,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'customDialog',
      'child': child,
      if (dismissible != null) 'dismissible': dismissible,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Renders a compact dashboard tile — the widget equivalent of the `ApplicationDefinition.dashboard` field (see [`11_Bundle_Metadata.md`](11_Bundle_Metadata.md) §11). Used to embed a dashboard-mode tile inside a page (launcher / app grid scenarios).
  static Map<String, dynamic> dashboard({
    dynamic content,
    num? refreshInterval,
    dynamic onTap,
  }) {
    return <String, dynamic>{
      'type': 'dashboard',
      if (content != null) 'content': content,
      if (refreshInterval != null) 'refreshInterval': refreshInterval,
      if (onTap != null) 'onTap': onTap,
    };
  }

  /// Material-style sortable, selectable data table bound to a row array.
  static Map<String, dynamic> dataTable({
    required dynamic columns,
    required String columns___key,
    required String columns___label,
    num? columns___width,
    bool? columns___sortable,
    String? columns___align,
    required dynamic rows,
    bool? selectable,
    dynamic sortColumn,
    dynamic sortAscending,
    dynamic onSort,
    dynamic onRowTap,
  }) {
    return <String, dynamic>{
      'type': 'dataTable',
      'columns': columns,
      'columns[].key': columns___key,
      'columns[].label': columns___label,
      if (columns___width != null) 'columns[].width': columns___width,
      if (columns___sortable != null) 'columns[].sortable': columns___sortable,
      if (columns___align != null) 'columns[].align': columns___align,
      'rows': rows,
      if (selectable != null) 'selectable': selectable,
      if (sortColumn != null) 'sortColumn': sortColumn,
      if (sortAscending != null) 'sortAscending': sortAscending,
      if (onSort != null) 'onSort': onSort,
      if (onRowTap != null) 'onRowTap': onRowTap,
    };
  }

  /// Date input with calendar/text entry modes. Shared rows per §2.6.0; `value` is an ISO date string.
  static Map<String, dynamic> dateField({
    String? label,
    String? format,
    String? firstDate,
    String? lastDate,
    String? mode,
    String? locale,
  }) {
    return <String, dynamic>{
      'type': 'dateField',
      if (label != null) 'label': label,
      if (format != null) 'format': format,
      if (firstDate != null) 'firstDate': firstDate,
      if (lastDate != null) 'lastDate': lastDate,
      if (mode != null) 'mode': mode,
      if (locale != null) 'locale': locale,
    };
  }

  /// Standalone date picker surface. Shared rows per §2.6.0; `value` is an ISO date string.
  static Map<String, dynamic> datePicker({
    String? firstDate,
    String? lastDate,
  }) {
    return <String, dynamic>{
      'type': 'datePicker',
      if (firstDate != null) 'firstDate': firstDate,
      if (lastDate != null) 'lastDate': lastDate,
    };
  }

  /// Date range selection. Exception to §2.6.0: instead of a single `binding`, the range is bound via **two separate properties** — `startDate` and `endDate` — each independently following §2.6.0 two-way semantics (each accepts a literal ISO string, a `{{path}}` expression for read-only display, or a plain state-path string for two-way binding). `firstDate`/`lastDate` remain one-way constraints on the allowed range.
  static Map<String, dynamic> dateRangePicker({
    String? startDate,
    String? endDate,
    String? label,
    String? firstDate,
    String? lastDate,
    String? format,
    String? locale,
    bool? enabled,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'dateRangePicker',
      if (startDate != null) 'startDate': startDate,
      if (endDate != null) 'endDate': endDate,
      if (label != null) 'label': label,
      if (firstDate != null) 'firstDate': firstDate,
      if (lastDate != null) 'lastDate': lastDate,
      if (format != null) 'format': format,
      if (locale != null) 'locale': locale,
      if (enabled != null) 'enabled': enabled,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Wraps a child with a decoration box (color, gradient, border, shadow,
  /// image, blur) without otherwise affecting layout. The full
  /// `BoxDecoration` may be supplied via `decoration:`, or any of its
  /// fields may appear flat at the top level for ergonomic shorthand.
  static Map<String, dynamic> decoration({
    dynamic decoration,
    dynamic color,
    dynamic borderRadius,
    dynamic border,
    dynamic gradient,
    dynamic image,
    dynamic boxShadow,
    String? shape,
    num? backdropBlur,
    dynamic child,
    dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'decoration',
      if (decoration != null) 'decoration': decoration,
      if (color != null) 'color': color,
      if (borderRadius != null) 'borderRadius': borderRadius,
      if (border != null) 'border': border,
      if (gradient != null) 'gradient': gradient,
      if (image != null) 'image': image,
      if (boxShadow != null) 'boxShadow': boxShadow,
      if (shape != null) 'shape': shape,
      if (backdropBlur != null) 'backdropBlur': backdropBlur,
      if (child != null) 'child': child,
      if (children != null) 'children': children,
    };
  }

  /// Horizontal separator.
  static Map<String, dynamic> divider({
    num? thickness,
    String? color,
    num? indent,
    num? endIndent,
  }) {
    return <String, dynamic>{
      'type': 'divider',
      if (thickness != null) 'thickness': thickness,
      if (color != null) 'color': color,
      if (indent != null) 'indent': indent,
      if (endIndent != null) 'endIndent': endIndent,
    };
  }

  /// Drop area that accepts dragged data.
  static Map<String, dynamic> dragTarget({
    dynamic canDrop,
    dynamic builder,
    dynamic children,
    dynamic onDrop,
    dynamic onDragEnter,
    dynamic onDragLeave,
  }) {
    return <String, dynamic>{
      'type': 'dragTarget',
      if (canDrop != null) 'canDrop': canDrop,
      if (builder != null) 'builder': builder,
      if (children != null) 'children': children,
      if (onDrop != null) 'onDrop': onDrop,
      if (onDragEnter != null) 'onDragEnter': onDragEnter,
      if (onDragLeave != null) 'onDragLeave': onDragLeave,
    };
  }

  /// Drag source widget that produces drag data and feedback visuals.
  static Map<String, dynamic> draggable({
    required dynamic data,
    dynamic feedback,
    dynamic childWhenDragging,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'draggable',
      'data': data,
      if (feedback != null) 'feedback': feedback,
      if (childWhenDragging != null) 'childWhenDragging': childWhenDragging,
      'child': child,
    };
  }

  /// Side navigation drawer. Each item's text field is `label`.
  static Map<String, dynamic> drawer({
    dynamic items,
    dynamic children,
    dynamic header,
    dynamic onSelect,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'drawer',
      if (items != null) 'items': items,
      if (children != null) 'children': children,
      if (header != null) 'header': header,
      if (onSelect != null) 'onSelect': onSelect,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Catches render and build errors thrown by descendants and displays a fallback UI. See [`06_Runtime_Contract.md`](06_Runtime_Contract.md) for the exact recovery lifecycle.
  static Map<String, dynamic> errorBoundary({
    required dynamic child,
    dynamic fallback,
    dynamic onError,
  }) {
    return <String, dynamic>{
      'type': 'errorBoundary',
      'child': child,
      if (fallback != null) 'fallback': fallback,
      if (onError != null) 'onError': onError,
    };
  }

  /// Retry-oriented variant of `errorBoundary`. The `handlers` map may route specific error types to distinct fallbacks.
  static Map<String, dynamic> errorRecovery({
    dynamic child,
    dynamic children,
    dynamic fallback,
    dynamic handlers,
    dynamic onError,
    bool? showDetails,
  }) {
    return <String, dynamic>{
      'type': 'errorRecovery',
      if (child != null) 'child': child,
      if (children != null) 'children': children,
      if (fallback != null) 'fallback': fallback,
      if (handlers != null) 'handlers': handlers,
      if (onError != null) 'onError': onError,
      if (showDetails != null) 'showDetails': showDetails,
    };
  }

  /// Flex child that expands to fill available space inside a `linear` parent.
  static Map<String, dynamic> expanded({
    num? flex,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'expanded',
      if (flex != null) 'flex': flex,
      'child': child,
    };
  }

  /// File and directory browser.
  static Map<String, dynamic> fileExplorer({
    dynamic items,
    String? rootPath,
    dynamic files,
    dynamic directories,
    bool? showIcons,
    bool? showHidden,
    bool? expandAll,
    num? width,
    num? height,
    String? selectedColor,
    dynamic onSelect,
    dynamic onOpen,
  }) {
    return <String, dynamic>{
      'type': 'fileExplorer',
      if (items != null) 'items': items,
      if (rootPath != null) 'rootPath': rootPath,
      if (files != null) 'files': files,
      if (directories != null) 'directories': directories,
      if (showIcons != null) 'showIcons': showIcons,
      if (showHidden != null) 'showHidden': showHidden,
      if (expandAll != null) 'expandAll': expandAll,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (selectedColor != null) 'selectedColor': selectedColor,
      if (onSelect != null) 'onSelect': onSelect,
      if (onOpen != null) 'onOpen': onOpen,
    };
  }

  /// Scales and aligns its child to fit available space.
  static Map<String, dynamic> fittedBox({
    String? fit,
    dynamic alignment,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'fittedBox',
      if (fit != null) 'fit': fit,
      if (alignment != null) 'alignment': alignment,
      'child': child,
    };
  }

  /// Flex child that may occupy up to its natural size.
  static Map<String, dynamic> flexible({
    num? flex,
    String? fit,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'flexible',
      if (flex != null) 'flex': flex,
      if (fit != null) 'fit': fit,
      'child': child,
    };
  }

  /// Floating action button (FAB).
  static Map<String, dynamic> floatingActionButton({
    String? icon,
    String? label,
    dynamic onTap,
  }) {
    return <String, dynamic>{
      'type': 'floatingActionButton',
      if (icon != null) 'icon': icon,
      if (label != null) 'label': label,
      if (onTap != null) 'onTap': onTap,
    };
  }

  /// Lightweight flowing layout that places each child along the main axis with fixed `spacing`, falling back to a new run when space is exhausted. A simpler alternative to `wrap` (§2.4.11) for spacer-style chains.
  static Map<String, dynamic> flow({
    required dynamic children,
    String? direction,
    num? spacing,
    String? alignment,
  }) {
    return <String, dynamic>{
      'type': 'flow',
      'children': children,
      if (direction != null) 'direction': direction,
      if (spacing != null) 'spacing': spacing,
      if (alignment != null) 'alignment': alignment,
    };
  }

  /// Container that manages validation state for its child inputs.
  static Map<String, dynamic> form({
    required dynamic children,
    String? showErrorsOn,
    dynamic onSubmit,
  }) {
    return <String, dynamic>{
      'type': 'form',
      'children': children,
      if (showErrorsOn != null) 'showErrorsOn': showErrorsOn,
      if (onSubmit != null) 'onSubmit': onSubmit,
    };
  }

  /// Sizes the child as a fraction of the parent.
  static Map<String, dynamic> fractionallySized({
    num? widthFactor,
    num? heightFactor,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'fractionallySized',
      if (widthFactor != null) 'widthFactor': widthFactor,
      if (heightFactor != null) 'heightFactor': heightFactor,
      'child': child,
    };
  }

  /// Radial gauge for a value within a range.
  static Map<String, dynamic> gauge({
    required num value,
    num? min,
    num? max,
    dynamic segments,
    num? size,
    num? strokeWidth,
    String? backgroundColor,
    String? valueColor,
    bool? showLabel,
    String? labelFormat,
    num? startAngle,
    num? sweepAngle,
  }) {
    return <String, dynamic>{
      'type': 'gauge',
      'value': value,
      if (min != null) 'min': min,
      if (max != null) 'max': max,
      if (segments != null) 'segments': segments,
      if (size != null) 'size': size,
      if (strokeWidth != null) 'strokeWidth': strokeWidth,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (valueColor != null) 'valueColor': valueColor,
      if (showLabel != null) 'showLabel': showLabel,
      if (labelFormat != null) 'labelFormat': labelFormat,
      if (startAngle != null) 'startAngle': startAngle,
      if (sweepAngle != null) 'sweepAngle': sweepAngle,
    };
  }

  /// Detects touch and pointer gestures on its child.
  static Map<String, dynamic> gestureDetector({
    required dynamic child,
    dynamic onTap,
    dynamic onDoubleTap,
    dynamic onLongPress,
    dynamic onPanStart,
    dynamic onPanUpdate,
    dynamic onPanEnd,
  }) {
    return <String, dynamic>{
      'type': 'gestureDetector',
      'child': child,
      if (onTap != null) 'onTap': onTap,
      if (onDoubleTap != null) 'onDoubleTap': onDoubleTap,
      if (onLongPress != null) 'onLongPress': onLongPress,
      if (onPanStart != null) 'onPanStart': onPanStart,
      if (onPanUpdate != null) 'onPanUpdate': onPanUpdate,
      if (onPanEnd != null) 'onPanEnd': onPanEnd,
    };
  }

  /// Time-series / numeric data graph (line, bar, area, scatter) drawn on a single set of axes. For node/edge topology visualization use `networkGraph` (§10.13).
  static Map<String, dynamic> graph({
    dynamic data,
    String? chartType,
    num? width,
    num? height,
    bool? showGrid,
    bool? showLabels,
    dynamic lineColor,
    dynamic fillColor,
    dynamic gridColor,
    num? strokeWidth,
  }) {
    return <String, dynamic>{
      'type': 'graph',
      if (data != null) 'data': data,
      if (chartType != null) 'chartType': chartType,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (showGrid != null) 'showGrid': showGrid,
      if (showLabels != null) 'showLabels': showLabels,
      if (lineColor != null) 'lineColor': lineColor,
      if (fillColor != null) 'fillColor': fillColor,
      if (gridColor != null) 'gridColor': gridColor,
      if (strokeWidth != null) 'strokeWidth': strokeWidth,
    };
  }

  /// Scrollable two-dimensional collection.
  static Map<String, dynamic> grid({
    dynamic items,
    dynamic itemTemplate,
    dynamic children,
    required dynamic columns,
    num? rowGap,
    num? columnGap,
    num? itemAspectRatio,
  }) {
    return <String, dynamic>{
      'type': 'grid',
      if (items != null) 'items': items,
      if (itemTemplate != null) 'itemTemplate': itemTemplate,
      if (children != null) 'children': children,
      'columns': columns,
      if (rowGap != null) 'rowGap': rowGap,
      if (columnGap != null) 'columnGap': columnGap,
      if (itemAspectRatio != null) 'itemAspectRatio': itemAspectRatio,
    };
  }

  /// Application header / toolbar at the top of a page.
  static Map<String, dynamic> headerBar({
    dynamic title,
    dynamic leading,
    dynamic actions,
    dynamic exitButton,
    String? backgroundColor,
    num? elevation,
    bool? centerTitle,
  }) {
    return <String, dynamic>{
      'type': 'headerBar',
      if (title != null) 'title': title,
      if (leading != null) 'leading': leading,
      if (actions != null) 'actions': actions,
      if (exitButton != null) 'exitButton': exitButton,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (elevation != null) 'elevation': elevation,
      if (centerTitle != null) 'centerTitle': centerTitle,
    };
  }

  /// Two-dimensional heatmap visualization.
  static Map<String, dynamic> heatmap({
    required dynamic data,
    dynamic columnLabels,
    dynamic rowLabels,
    num? cellSize,
    dynamic colorRange,
    bool? showValues,
    dynamic onCellTap,
  }) {
    return <String, dynamic>{
      'type': 'heatmap',
      'data': data,
      if (columnLabels != null) 'columnLabels': columnLabels,
      if (rowLabels != null) 'rowLabels': rowLabels,
      if (cellSize != null) 'cellSize': cellSize,
      if (colorRange != null) 'colorRange': colorRange,
      if (showValues != null) 'showValues': showValues,
      if (onCellTap != null) 'onCellTap': onCellTap,
    };
  }

  /// Shared-element transition wrapper. Wrap a child widget on the
  /// source page AND on the destination page with the SAME `tag`; the
  /// runtime morphs the source widget's bounds → destination widget's
  /// bounds during the route transition (cover → detail magnification,
  /// album cover → expanded album view). Pairs naturally with
  /// `RouteTransition` styles such as `fade` or `sharedAxis`.
  static Map<String, dynamic> hero({
    required String tag,
    required dynamic child,
    bool? transitionOnUserGestures,
    dynamic flightShuttleBuilder,
  }) {
    return <String, dynamic>{
      'type': 'hero',
      'tag': tag,
      'child': child,
      if (transitionOnUserGestures != null) 'transitionOnUserGestures': transitionOnUserGestures,
      if (flightShuttleBuilder != null) 'flightShuttleBuilder': flightShuttleBuilder,
    };
  }

  /// Displays an icon. The `icon` property accepts five source forms — pick
  /// the lightest option that fits the asset:
  /// 
  /// 1. **Named (built-in)** — `"home"`, `"folder_open"`, … from the runtime's
  /// Material Icons resolver table. Zero-cost.
  /// 2. **Codepoint** — `{codepoint, fontFamily?, fontPackage?}` for Material
  /// Icons codepoints not in the name table.
  /// 3. **URL** — `https://…` or `http://…` (raster or SVG). Fetched and cached
  /// at first render.
  /// 4. **Bundle SVG asset** — `assets/icons/<name>.svg` resolved from the bundle
  /// asset map. Used for app-specific icon sets shipped with the bundle.
  /// 5. **Local SVG inline** — `data:image/svg+xml;…` data URI for one-off icons
  /// embedded directly in the DSL.
  /// 
  /// The optional `shader` field paints the icon with a gradient/shader fill
  /// (rather than a solid `color`). When both are set the shader wins.
  static Map<String, dynamic> icon({
    required dynamic icon,
    String? size,
    String? sizeToken,
    dynamic color,
    dynamic shader,
  }) {
    return <String, dynamic>{
      'type': 'icon',
      'icon': icon,
      if (size != null) 'size': size,
      if (sizeToken != null) 'sizeToken': sizeToken,
      if (color != null) 'color': color,
      if (shader != null) 'shader': shader,
    };
  }

  /// Icon-only button for compact actions.
  static Map<String, dynamic> iconButton({
    required String icon,
    num? size,
    String? color,
    bool? enabled,
    dynamic onTap,
  }) {
    return <String, dynamic>{
      'type': 'iconButton',
      'icon': icon,
      if (size != null) 'size': size,
      if (color != null) 'color': color,
      if (enabled != null) 'enabled': enabled,
      if (onTap != null) 'onTap': onTap,
    };
  }

  /// Displays an image from a URL, bundle, or client resource.
  static Map<String, dynamic> image({
    required String src,
    num? width,
    num? height,
    String? fit,
    dynamic alignment,
  }) {
    return <String, dynamic>{
      'type': 'image',
      'src': src,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (fit != null) 'fit': fit,
      if (alignment != null) 'alignment': alignment,
    };
  }

  /// Wraps a child with a colour / blur filter. Distinct from
  /// `BoxDecoration.image.colorFilter` (which colours an image
  /// background) — `imageFilter` filters the entire rendered subtree.
  /// Use for sepia/grayscale book pages, blur-on-hover thumbnails,
  /// saturation-bumped hero shots.
  static Map<String, dynamic> imageFilter({
    required String filter,
    num? intensity,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'imageFilter',
      'filter': filter,
      if (intensity != null) 'intensity': intensity,
      'child': child,
    };
  }

  /// Displays a single child selected by index. All children retain state.
  static Map<String, dynamic> indexedStack({
    dynamic index,
    dynamic alignment,
    required dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'indexedStack',
      if (index != null) 'index': index,
      if (alignment != null) 'alignment': alignment,
      'children': children,
    };
  }

  /// Material-style touch feedback with ripple effect.
  static Map<String, dynamic> inkWell({
    required dynamic child,
    num? borderRadius,
    dynamic onTap,
    dynamic onLongPress,
  }) {
    return <String, dynamic>{
      'type': 'inkWell',
      'child': child,
      if (borderRadius != null) 'borderRadius': borderRadius,
      if (onTap != null) 'onTap': onTap,
      if (onLongPress != null) 'onLongPress': onLongPress,
    };
  }

  /// Constrains a child to the intrinsic height required by its content.
  static Map<String, dynamic> intrinsicHeight({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'intrinsicHeight',
      'child': child,
    };
  }

  /// Constrains a child to the intrinsic width required by its content.
  static Map<String, dynamic> intrinsicWidth({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'intrinsicWidth',
      'child': child,
    };
  }

  /// Image with an automatic slow zoom-and-pan animation (the "Ken
  /// Burns effect"). Used for cinematic stills in book chapter
  /// openings, landing pages, and slideshow frames. The image holds
  /// intrinsic resolution and is animated within fit-bounds — no
  /// cropping outside the rendered rectangle.
  static Map<String, dynamic> kenBurnsImage({
    required dynamic src,
    dynamic duration,
    num? intensity,
    dynamic startAlignment,
    dynamic endAlignment,
    bool? loop,
    dynamic curve,
    dynamic width,
    dynamic height,
    String? fit,
  }) {
    return <String, dynamic>{
      'type': 'kenBurnsImage',
      'src': src,
      if (duration != null) 'duration': duration,
      if (intensity != null) 'intensity': intensity,
      if (startAlignment != null) 'startAlignment': startAlignment,
      if (endAlignment != null) 'endAlignment': endAlignment,
      if (loop != null) 'loop': loop,
      if (curve != null) 'curve': curve,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (fit != null) 'fit': fit,
    };
  }

  /// Runtime-only responsive container: picks a child by matching the current constraints against a breakpoint map.
  static Map<String, dynamic> layoutBuilder({
    dynamic breakpoints,
    dynamic layouts,
    dynamic default_,
  }) {
    return <String, dynamic>{
      'type': 'layoutBuilder',
      if (breakpoints != null) 'breakpoints': breakpoints,
      if (layouts != null) 'layouts': layouts,
      if (default_ != null) 'default': default_,
    };
  }

  /// Defer rendering of an expensive subtree until it enters the viewport (or until explicitly loaded). `lazy` belongs to the Utility group in [`02_Widgets.md`](02_Widgets.md) and is listed here because its schema pairs conceptually with the heavy Advanced widgets above.
  static Map<String, dynamic> lazy({
    dynamic placeholder,
    dynamic content,
    dynamic children,
    String? trigger,
    dynamic onLoad,
    dynamic onError,
  }) {
    return <String, dynamic>{
      'type': 'lazy',
      if (placeholder != null) 'placeholder': placeholder,
      if (content != null) 'content': content,
      if (children != null) 'children': children,
      if (trigger != null) 'trigger': trigger,
      if (onLoad != null) 'onLoad': onLoad,
      if (onError != null) 'onError': onError,
    };
  }

  /// Full-screen modal image viewer with pinch-zoom and swipe-between-
  /// images. Used as a tap target on a thumbnail image — opening the
  /// lightbox transitions the thumbnail into the full-screen view.
  /// Pairs naturally with `hero` for the cover-to-detail morph.
  static Map<String, dynamic> lightbox({
    required dynamic images,
    num? initialIndex,
    bool? allowZoom,
    num? maxZoom,
    bool? allowSwipe,
    dynamic backgroundColor,
    dynamic onIndexChanged,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'lightbox',
      'images': images,
      if (initialIndex != null) 'initialIndex': initialIndex,
      if (allowZoom != null) 'allowZoom': allowZoom,
      if (maxZoom != null) 'maxZoom': maxZoom,
      if (allowSwipe != null) 'allowSwipe': allowSwipe,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (onIndexChanged != null) 'onIndexChanged': onIndexChanged,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Limits a child's size only when it would otherwise be unbounded.
  static Map<String, dynamic> limitedBox({
    num? maxWidth,
    num? maxHeight,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'limitedBox',
      if (maxWidth != null) 'maxWidth': maxWidth,
      if (maxHeight != null) 'maxHeight': maxHeight,
      'child': child,
    };
  }

  /// Linear (flex) layout along a single axis. Replaces separate `row` / `column` widgets — use `direction: "horizontal"` or `direction: "vertical"`.
  /// 
  /// Main-axis sizing: when at least one child is `expanded` / `flexible` / `spacer` (or carries a `flex` value), `linear` expands to fill the available main-axis space so those children can distribute the remainder; otherwise it shrink-wraps its children. Authors can override this with the explicit `mainAxisSize` property.
  static Map<String, dynamic> linear({
    String? mainAxisSize,
    required String direction,
    String? alignment,
    String? distribution,
    num? spacing,
    required dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'linear',
      if (mainAxisSize != null) 'mainAxisSize': mainAxisSize,
      'direction': direction,
      if (alignment != null) 'alignment': alignment,
      if (distribution != null) 'distribution': distribution,
      if (spacing != null) 'spacing': spacing,
      'children': children,
    };
  }

  /// Scrollable linear collection rendered from an array binding.
  static Map<String, dynamic> list({
    dynamic items,
    dynamic itemTemplate,
    dynamic children,
    num? spacing,
    String? orientation,
    String? emptyMessage,
    num? itemExtent,
  }) {
    return <String, dynamic>{
      'type': 'list',
      if (items != null) 'items': items,
      if (itemTemplate != null) 'itemTemplate': itemTemplate,
      if (children != null) 'children': children,
      if (spacing != null) 'spacing': spacing,
      if (orientation != null) 'orientation': orientation,
      if (emptyMessage != null) 'emptyMessage': emptyMessage,
      if (itemExtent != null) 'itemExtent': itemExtent,
    };
  }

  /// Single row in a list with optional leading/trailing widgets. Replaces Material `listTile` naming.
  static Map<String, dynamic> listItem({
    dynamic title,
    dynamic subtitle,
    dynamic leading,
    dynamic trailing,
    dynamic onTap,
    bool? selected,
    bool? enabled,
  }) {
    return <String, dynamic>{
      'type': 'listItem',
      if (title != null) 'title': title,
      if (subtitle != null) 'subtitle': subtitle,
      if (leading != null) 'leading': leading,
      if (trailing != null) 'trailing': trailing,
      if (onTap != null) 'onTap': onTap,
      if (selected != null) 'selected': selected,
      if (enabled != null) 'enabled': enabled,
    };
  }

  /// Embedded Lottie/JSON animation playback.
  static Map<String, dynamic> lottieAnimation({
    required String src,
    bool? autoPlay,
    bool? loop,
  }) {
    return <String, dynamic>{
      'type': 'lottieAnimation',
      'src': src,
      if (autoPlay != null) 'autoPlay': autoPlay,
      if (loop != null) 'loop': loop,
    };
  }

  /// Geographic map with markers and overlays.
  static Map<String, dynamic> map({
    dynamic center,
    num? latitude,
    num? longitude,
    num? zoom,
    String? mapType,
    dynamic markers,
    required String markers___id,
    required num markers___latitude,
    required num markers___longitude,
    String? markers___label,
    String? markers___icon,
    String? markers___color,
    dynamic overlays,
    required String overlays___type,
    dynamic overlays___points,
    String? overlays___fillColor,
    String? overlays___strokeColor,
    num? overlays___strokeWidth,
    dynamic onMarkerTap,
    dynamic onMapTap,
  }) {
    return <String, dynamic>{
      'type': 'map',
      if (center != null) 'center': center,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
      if (zoom != null) 'zoom': zoom,
      if (mapType != null) 'mapType': mapType,
      if (markers != null) 'markers': markers,
      'markers[].id': markers___id,
      'markers[].latitude': markers___latitude,
      'markers[].longitude': markers___longitude,
      if (markers___label != null) 'markers[].label': markers___label,
      if (markers___icon != null) 'markers[].icon': markers___icon,
      if (markers___color != null) 'markers[].color': markers___color,
      if (overlays != null) 'overlays': overlays,
      'overlays[].type': overlays___type,
      if (overlays___points != null) 'overlays[].points': overlays___points,
      if (overlays___fillColor != null) 'overlays[].fillColor': overlays___fillColor,
      if (overlays___strokeColor != null) 'overlays[].strokeColor': overlays___strokeColor,
      if (overlays___strokeWidth != null) 'overlays[].strokeWidth': overlays___strokeWidth,
      if (onMarkerTap != null) 'onMarkerTap': onMarkerTap,
      if (onMapTap != null) 'onMapTap': onMapTap,
    };
  }

  /// Applies outer margin around a single child.
  static Map<String, dynamic> margin({
    required dynamic margin,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'margin',
      'margin': margin,
      'child': child,
    };
  }

  /// Markdown renderer.
  static Map<String, dynamic> markdown({
    dynamic text,
    bool? selectable,
    num? width,
    num? height,
    num? fontSize,
    String? textColor,
    String? linkColor,
    String? codeBackgroundColor,
    dynamic onLinkTap,
  }) {
    return <String, dynamic>{
      'type': 'markdown',
      if (text != null) 'text': text,
      if (selectable != null) 'selectable': selectable,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (fontSize != null) 'fontSize': fontSize,
      if (textColor != null) 'textColor': textColor,
      if (linkColor != null) 'linkColor': linkColor,
      if (codeBackgroundColor != null) 'codeBackgroundColor': codeBackgroundColor,
      if (onLinkTap != null) 'onLinkTap': onLinkTap,
    };
  }

  /// Audio / video player widget.
  static Map<String, dynamic> mediaPlayer({
    required dynamic source,
    String? mediaType,
    bool? autoPlay,
    bool? loop,
    bool? muted,
    num? volume,
    bool? controls,
    dynamic poster,
    bool? waveform,
    num? width,
    num? height,
    dynamic onPlay,
    dynamic onPause,
    dynamic onEnded,
    dynamic onTimeUpdate,
    dynamic onError,
  }) {
    return <String, dynamic>{
      'type': 'mediaPlayer',
      'source': source,
      if (mediaType != null) 'mediaType': mediaType,
      if (autoPlay != null) 'autoPlay': autoPlay,
      if (loop != null) 'loop': loop,
      if (muted != null) 'muted': muted,
      if (volume != null) 'volume': volume,
      if (controls != null) 'controls': controls,
      if (poster != null) 'poster': poster,
      if (waveform != null) 'waveform': waveform,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (onPlay != null) 'onPlay': onPlay,
      if (onPause != null) 'onPause': onPause,
      if (onEnded != null) 'onEnded': onEnded,
      if (onTimeUpdate != null) 'onTimeUpdate': onTimeUpdate,
      if (onError != null) 'onError': onError,
    };
  }

  /// Responsive widget that inspects the current layout context and picks a child based on media-query conditions. Supports a `then`/`else` expression form and a `breakpoints` map form. The binding engine exposes `{{media.width}}`, `{{media.height}}`, `{{media.orientation}}` inside `condition`.
  static Map<String, dynamic> mediaQuery({
    dynamic condition,
    dynamic then,
    dynamic else_,
    dynamic breakpoints,
    dynamic defaultChild,
  }) {
    return <String, dynamic>{
      'type': 'mediaQuery',
      if (condition != null) 'condition': condition,
      if (then != null) 'then': then,
      if (else_ != null) 'else': else_,
      if (breakpoints != null) 'breakpoints': breakpoints,
      if (defaultChild != null) 'defaultChild': defaultChild,
    };
  }

  /// Vertical navigation rail for tablet/desktop layouts. Each item's text field is `label`.
  static Map<String, dynamic> navigationRail({
    dynamic selectedIndex,
    required dynamic items,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'navigationRail',
      if (selectedIndex != null) 'selectedIndex': selectedIndex,
      'items': items,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Network topology graph. Same node/edge model as `graph`, with topology-oriented defaults (hierarchical layout, directed edges).
  static Map<String, dynamic> networkGraph() {
    return <String, dynamic>{
      'type': 'networkGraph',
    };
  }

  /// Specialized input for numeric values. Shared rows per §2.6.0; `value` is `number`.
  static Map<String, dynamic> numberField({
    String? label,
    num? min,
    num? max,
    num? step,
    num? decimalPlaces,
    String? prefix,
    String? suffix,
    String? thousandSeparator,
  }) {
    return <String, dynamic>{
      'type': 'numberField',
      if (label != null) 'label': label,
      if (min != null) 'min': min,
      if (max != null) 'max': max,
      if (step != null) 'step': step,
      if (decimalPlaces != null) 'decimalPlaces': decimalPlaces,
      if (prefix != null) 'prefix': prefix,
      if (suffix != null) 'suffix': suffix,
      if (thousandSeparator != null) 'thousandSeparator': thousandSeparator,
    };
  }

  /// Incremental numeric input with plus/minus buttons. Shared rows per §2.6.0; `value` is `number`.
  static Map<String, dynamic> numberStepper({
    num? min,
    num? max,
    num? step,
  }) {
    return <String, dynamic>{
      'type': 'numberStepper',
      if (min != null) 'min': min,
      if (max != null) 'max': max,
      if (step != null) 'step': step,
    };
  }

  /// Swaps between an online widget and an offline fallback based on connectivity tracked by the runtime. Connectivity state may be pinned by an `isOnline` binding for tests.
  static Map<String, dynamic> offlineFallback({
    dynamic online,
    dynamic offline,
    String? message,
    String? icon,
    bool? showRetry,
    dynamic onRetry,
    dynamic isOnline,
  }) {
    return <String, dynamic>{
      'type': 'offlineFallback',
      if (online != null) 'online': online,
      if (offline != null) 'offline': offline,
      if (message != null) 'message': message,
      if (icon != null) 'icon': icon,
      if (showRetry != null) 'showRetry': showRetry,
      if (onRetry != null) 'onRetry': onRetry,
      if (isOnline != null) 'isOnline': isOnline,
    };
  }

  /// Wraps a child with opacity, with optional animation.
  static Map<String, dynamic> opacity({
    required dynamic opacity,
    bool? animated,
    num? duration,
    String? curve,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'opacity',
      'opacity': opacity,
      if (animated != null) 'animated': animated,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      'child': child,
    };
  }

  /// Applies padding around a single child.
  static Map<String, dynamic> padding({
    required dynamic padding,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'padding',
      'padding': padding,
      'child': child,
    };
  }

  /// Full-viewport paged scroll view. Snaps one page per swipe; ideal
  /// for book pages, photo galleries, onboarding flows. Distinct from
  /// `carousel` (partial-viewport, peeking neighbours) — pageView is
  /// always one full page. Each child is rendered as a separate page.
  static Map<String, dynamic> pageView({
    String? direction,
    required dynamic children,
    num? initialPage,
    bool? loop,
    String? scrollPhysics,
    bool? allowImplicitScrolling,
    dynamic onPageChanged,
  }) {
    return <String, dynamic>{
      'type': 'pageView',
      if (direction != null) 'direction': direction,
      'children': children,
      if (initialPage != null) 'initialPage': initialPage,
      if (loop != null) 'loop': loop,
      if (scrollPhysics != null) 'scrollPhysics': scrollPhysics,
      if (allowImplicitScrolling != null) 'allowImplicitScrolling': allowImplicitScrolling,
      if (onPageChanged != null) 'onPageChanged': onPageChanged,
    };
  }

  /// Presents a prompt for one or more client capabilities (e.g., clipboard, filesystem). See [`07_Security.md`](07_Security.md) for the permission vocabulary.
  static Map<String, dynamic> permissionPrompt({
    dynamic permissions,
    String? permissionType,
    String? style,
    String? title,
    String? description,
    String? icon,
    bool? allowPartial,
    dynamic onAllow,
    dynamic onDeny,
  }) {
    return <String, dynamic>{
      'type': 'permissionPrompt',
      if (permissions != null) 'permissions': permissions,
      if (permissionType != null) 'permissionType': permissionType,
      if (style != null) 'style': style,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (icon != null) 'icon': icon,
      if (allowPartial != null) 'allowPartial': allowPartial,
      if (onAllow != null) 'onAllow': onAllow,
      if (onDeny != null) 'onDeny': onDeny,
    };
  }

  /// Empty placeholder widget with optional dimensions and color.
  static Map<String, dynamic> placeholder({
    num? fallbackWidth,
    num? fallbackHeight,
    String? color,
    num? strokeWidth,
    dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'placeholder',
      if (fallbackWidth != null) 'fallbackWidth': fallbackWidth,
      if (fallbackHeight != null) 'fallbackHeight': fallbackHeight,
      if (color != null) 'color': color,
      if (strokeWidth != null) 'strokeWidth': strokeWidth,
      if (child != null) 'child': child,
    };
  }

  /// Button that reveals a popup menu of options.
  static Map<String, dynamic> popupMenuButton({
    String? icon,
    required dynamic items,
    dynamic onSelect,
  }) {
    return <String, dynamic>{
      'type': 'popupMenuButton',
      if (icon != null) 'icon': icon,
      'items': items,
      if (onSelect != null) 'onSelect': onSelect,
    };
  }

  /// Positions a child within a `stack` using offsets.
  static Map<String, dynamic> positioned({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'positioned',
      'child': child,
    };
  }

  /// Progress indicator (linear or circular).
  static Map<String, dynamic> progressBar({
    dynamic value,
    String? indicatorType,
    String? color,
    String? backgroundColor,
  }) {
    return <String, dynamic>{
      'type': 'progressBar',
      if (value != null) 'value': value,
      if (indicatorType != null) 'indicatorType': indicatorType,
      if (color != null) 'color': color,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
    };
  }

  /// Single radio button. The group's selected value is bound via `groupValue` (or the enclosing `radioGroup`'s `binding`).
  static Map<String, dynamic> radio({
    required dynamic value,
    required dynamic groupValue,
    String? label,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'radio',
      'value': value,
      'groupValue': groupValue,
      if (label != null) 'label': label,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Single-selection radio group. Shared rows per §2.6.0.
  static Map<String, dynamic> radioGroup({
    required dynamic options,
    String? orientation,
  }) {
    return <String, dynamic>{
      'type': 'radioGroup',
      'options': options,
      if (orientation != null) 'orientation': orientation,
    };
  }

  /// Range selection with two thumbs. Shared rows per §2.6.0; `value` is an object `{ start, end }`.
  static Map<String, dynamic> rangeSlider({
    num? min,
    num? max,
    num? divisions,
  }) {
    return <String, dynamic>{
      'type': 'rangeSlider',
      if (min != null) 'min': min,
      if (max != null) 'max': max,
      if (divisions != null) 'divisions': divisions,
    };
  }

  /// Discrete rating control (e.g., star rating). Shared rows per §2.6.0; `value` is `number`.
  static Map<String, dynamic> rating({
    num? max,
    String? icon,
    String? color,
  }) {
    return <String, dynamic>{
      'type': 'rating',
      if (max != null) 'max': max,
      if (icon != null) 'icon': icon,
      if (color != null) 'color': color,
    };
  }

  /// Multi-span styled text — paragraph composition for long-form content
  /// (articles, book chapters, captions with inline emphasis or icons).
  /// Each `Span` is either a styled text run or an inline widget; the
  /// paragraph-level `style` provides the base TextStyle that individual
  /// span styles layer on top of.
  static Map<String, dynamic> richText({
    required dynamic spans,
    dynamic style,
    dynamic dropCap,
    String? textAlign,
    String? textDirection,
    num? maxLines,
    String? overflow,
    bool? softWrap,
  }) {
    return <String, dynamic>{
      'type': 'richText',
      'spans': spans,
      if (style != null) 'style': style,
      if (dropCap != null) 'dropCap': dropCap,
      if (textAlign != null) 'textAlign': textAlign,
      if (textDirection != null) 'textDirection': textDirection,
      if (maxLines != null) 'maxLines': maxLines,
      if (overflow != null) 'overflow': overflow,
      if (softWrap != null) 'softWrap': softWrap,
    };
  }

  /// Plays a Rive animation (`.riv` asset) — the alternative to
  /// `lottieAnimation` when the asset was authored in Rive. State-machine
  /// inputs are driven via `inputs` so the same asset reacts to host
  /// state changes (toggle, scrub, trigger). Distinct from Lottie:
  /// Rive supports interactive state machines, vector deformation, and
  /// smaller binary footprints; Lottie is After Effects-based and
  /// better suited to time-driven motion graphics.
  static Map<String, dynamic> rive({
    required dynamic src,
    String? artboard,
    String? animation,
    String? stateMachine,
    dynamic inputs,
    String? fit,
    dynamic alignment,
    dynamic width,
    dynamic height,
  }) {
    return <String, dynamic>{
      'type': 'rive',
      'src': src,
      if (artboard != null) 'artboard': artboard,
      if (animation != null) 'animation': animation,
      if (stateMachine != null) 'stateMachine': stateMachine,
      if (inputs != null) 'inputs': inputs,
      if (fit != null) 'fit': fit,
      if (alignment != null) 'alignment': alignment,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
    };
  }

  /// Insets children so they avoid system UI overlaps (notch, status bar, home indicator).
  static Map<String, dynamic> safeArea({
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'safeArea',
      'child': child,
    };
  }

  /// Animation driven by scroll position rather than time. Wraps a
  /// child and reads from an ancestor scroll view's offset. Each
  /// `binding` maps a scroll-offset window to a property tween — when
  /// scroll passes through `[fromOffset, toOffset]` the property
  /// interpolates between `fromValue` and `toValue` linearly (or via
  /// `curve`).
  /// 
  /// Common uses: parallax masthead (image translates 50% scroll
  /// speed), reveal-on-scroll (fade in as element enters viewport),
  /// shrinking title (font scales as user scrolls down).
  static Map<String, dynamic> scrollAnimated({
    required dynamic bindings,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'scrollAnimated',
      'bindings': bindings,
      'child': child,
    };
  }

  /// Wraps a scrollable child with a visible scroll bar.
  /// 
  /// The runtime MUST provide a shared scroll controller to both the scroll bar and its scrollable child. When `thumbVisibility` or `trackVisibility` is `true`, the controller is required to drive the visibility; omitting it is a runtime error. Authors SHOULD NOT manage the controller manually — the runtime injects it transparently so the child scrollable (`scrollView`, `singleChildScrollView`, `list`, `grid`, `pageView`) binds to the same position.
  static Map<String, dynamic> scrollBar({
    bool? thumbVisibility,
    bool? trackVisibility,
    num? thickness,
    num? radius,
    dynamic child,
    dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'scrollBar',
      if (thumbVisibility != null) 'thumbVisibility': thumbVisibility,
      if (trackVisibility != null) 'trackVisibility': trackVisibility,
      if (thickness != null) 'thickness': thickness,
      if (radius != null) 'radius': radius,
      if (child != null) 'child': child,
      if (children != null) 'children': children,
    };
  }

  /// Scrollable viewport. Two layout modes — pick one per instance:
  /// 
  /// - **Linear mode** — `child` (single widget) or `children` (wrapped
  /// in an implicit linear column along `direction`). Simplest for
  /// everyday scrolling content.
  /// - **Sliver mode** — `slivers` array of `Sliver` primitives. Use
  /// for collapsing app bars, sticky section headers, parallax
  /// mastheads, or mixing list/grid sections in one viewport.
  /// 
  /// The three input slots (`child`, `children`, `slivers`) are
  /// mutually exclusive.
  static Map<String, dynamic> scrollView({
    String? direction,
    dynamic padding,
    String? scrollPhysics,
    dynamic child,
    dynamic children,
    dynamic slivers,
  }) {
    return <String, dynamic>{
      'type': 'scrollView',
      if (direction != null) 'direction': direction,
      if (padding != null) 'padding': padding,
      if (scrollPhysics != null) 'scrollPhysics': scrollPhysics,
      if (child != null) 'child': child,
      if (children != null) 'children': children,
      if (slivers != null) 'slivers': slivers,
    };
  }

  /// Segmented selection, styled as tabs or buttons. Shared rows per §2.6.0.
  static Map<String, dynamic> segmentedControl({
    required dynamic options,
    String? variant,
  }) {
    return <String, dynamic>{
      'type': 'segmentedControl',
      'options': options,
      if (variant != null) 'variant': variant,
    };
  }

  /// Single-value dropdown selection. Shared rows per §2.6.0.
  static Map<String, dynamic> select({
    required dynamic options,
    String? placeholder,
  }) {
    return <String, dynamic>{
      'type': 'select',
      'options': options,
      if (placeholder != null) 'placeholder': placeholder,
    };
  }

  /// Signature capture pad.
  static Map<String, dynamic> signature({
    dynamic binding,
    String? penColor,
    num? penWidth,
    num? width,
    num? height,
    String? backgroundColor,
    String? borderColor,
    bool? showClearButton,
    bool? showGuide,
    dynamic onSignatureEnd,
    dynamic onClear,
  }) {
    return <String, dynamic>{
      'type': 'signature',
      if (binding != null) 'binding': binding,
      if (penColor != null) 'penColor': penColor,
      if (penWidth != null) 'penWidth': penWidth,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (borderColor != null) 'borderColor': borderColor,
      if (showClearButton != null) 'showClearButton': showClearButton,
      if (showGuide != null) 'showGuide': showGuide,
      if (onSignatureEnd != null) 'onSignatureEnd': onSignatureEnd,
      if (onClear != null) 'onClear': onClear,
    };
  }

  /// Dialog presenting a list of options.
  static Map<String, dynamic> simpleDialog({
    String? title,
    dynamic options,
    dynamic children,
    dynamic onSelect,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'simpleDialog',
      if (title != null) 'title': title,
      if (options != null) 'options': options,
      if (children != null) 'children': children,
      if (onSelect != null) 'onSelect': onSelect,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Lightweight scrollable wrapper for a single child.
  static Map<String, dynamic> singleChildScrollView({
    String? direction,
    dynamic padding,
    dynamic child,
    dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'singleChildScrollView',
      if (direction != null) 'direction': direction,
      if (padding != null) 'padding': padding,
      if (child != null) 'child': child,
      if (children != null) 'children': children,
    };
  }

  /// Fixed-size box. Commonly used as a spacer with an explicit size.
  static Map<String, dynamic> sizedBox({
    num? width,
    num? height,
    dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'sizedBox',
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (child != null) 'child': child,
    };
  }

  /// Continuous single-value selection. Shared rows per §2.6.0; `value` is `number`.
  static Map<String, dynamic> slider({
    num? value,
    num? min,
    num? max,
    num? divisions,
  }) {
    return <String, dynamic>{
      'type': 'slider',
      if (value != null) 'value': value,
      if (min != null) 'min': min,
      if (max != null) 'max': max,
      if (divisions != null) 'divisions': divisions,
    };
  }

  /// Transient notification at the bottom of the screen.
  static Map<String, dynamic> snackBar({
    required String content,
    num? duration,
    dynamic action,
    dynamic onClose,
  }) {
    return <String, dynamic>{
      'type': 'snackBar',
      'content': content,
      if (duration != null) 'duration': duration,
      if (action != null) 'action': action,
      if (onClose != null) 'onClose': onClose,
    };
  }

  /// Flexible empty space inside a `linear` parent.
  static Map<String, dynamic> spacer({
    num? flex,
  }) {
    return <String, dynamic>{
      'type': 'spacer',
      if (flex != null) 'flex': flex,
    };
  }

  /// Overlapping children. Non-positioned children align per `alignment`; positioned children use explicit offsets (see `positioned`).
  static Map<String, dynamic> stack({
    dynamic alignment,
    String? fit,
    required dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'stack',
      if (alignment != null) 'alignment': alignment,
      if (fit != null) 'fit': fit,
      'children': children,
    };
  }

  /// Pinterest-style masonry layout — items keep their intrinsic height
  /// and are packed by column without uniform row alignment. Use for
  /// album / book / portfolio shelves where covers have different
  /// aspect ratios. Distinct from `grid` (uniform row alignment) and
  /// `carousel` (single-axis scrolling).
  static Map<String, dynamic> staggeredGrid({
    dynamic items,
    dynamic itemTemplate,
    dynamic children,
    required dynamic columns,
    num? mainAxisSpacing,
    num? crossAxisSpacing,
    dynamic padding,
    String? scrollDirection,
  }) {
    return <String, dynamic>{
      'type': 'staggeredGrid',
      if (items != null) 'items': items,
      if (itemTemplate != null) 'itemTemplate': itemTemplate,
      if (children != null) 'children': children,
      'columns': columns,
      if (mainAxisSpacing != null) 'mainAxisSpacing': mainAxisSpacing,
      if (crossAxisSpacing != null) 'crossAxisSpacing': crossAxisSpacing,
      if (padding != null) 'padding': padding,
      if (scrollDirection != null) 'scrollDirection': scrollDirection,
    };
  }

  /// Step-by-step wizard. Shared `binding` / `value` / `enabled` / `onChange` per §2.6.0 — the bound value is the **active step index** (integer). `binding` and `currentStep` are aliases: when `binding` is set, it takes effect; otherwise `currentStep` is read as a one-way property.
  static Map<String, dynamic> stepper({
    required dynamic steps,
    dynamic currentStep,
    String? stepperType,
    dynamic onStepTapped,
    dynamic onStepContinue,
    dynamic onStepCancel,
  }) {
    return <String, dynamic>{
      'type': 'stepper',
      'steps': steps,
      if (currentStep != null) 'currentStep': currentStep,
      if (stepperType != null) 'stepperType': stepperType,
      if (onStepTapped != null) 'onStepTapped': onStepTapped,
      if (onStepContinue != null) 'onStepContinue': onStepContinue,
      if (onStepCancel != null) 'onStepCancel': onStepCancel,
    };
  }

  /// Horizontal tab selector. Each tab's text field is `label`.
  static Map<String, dynamic> tabBar({
    dynamic selectedIndex,
    required dynamic tabs,
    dynamic onChange,
  }) {
    return <String, dynamic>{
      'type': 'tabBar',
      if (selectedIndex != null) 'selectedIndex': selectedIndex,
      'tabs': tabs,
      if (onChange != null) 'onChange': onChange,
    };
  }

  /// Content area that displays widgets corresponding to the currently selected tab.
  static Map<String, dynamic> tabBarView({
    dynamic selectedIndex,
    required dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'tabBarView',
      if (selectedIndex != null) 'selectedIndex': selectedIndex,
      'children': children,
    };
  }

  /// Layout table for arranging widgets in rows and columns. Not data-bound; each cell is a widget.
  static Map<String, dynamic> table({
    required dynamic rows,
    dynamic border,
    dynamic defaultColumnWidth,
    String? defaultVerticalAlignment,
    dynamic columnWidths,
  }) {
    return <String, dynamic>{
      'type': 'table',
      'rows': rows,
      if (border != null) 'border': border,
      if (defaultColumnWidth != null) 'defaultColumnWidth': defaultColumnWidth,
      if (defaultVerticalAlignment != null) 'defaultVerticalAlignment': defaultVerticalAlignment,
      if (columnWidths != null) 'columnWidths': columnWidths,
    };
  }

  /// ANSI-capable terminal emulator.
  static Map<String, dynamic> terminal({
    dynamic lines,
    String? prompt,
    bool? showInput,
    num? maxLines,
    num? width,
    num? height,
    num? fontSize,
    String? backgroundColor,
    String? textColor,
    String? promptColor,
    dynamic onCommand,
  }) {
    return <String, dynamic>{
      'type': 'terminal',
      if (lines != null) 'lines': lines,
      if (prompt != null) 'prompt': prompt,
      if (showInput != null) 'showInput': showInput,
      if (maxLines != null) 'maxLines': maxLines,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (fontSize != null) 'fontSize': fontSize,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
      if (textColor != null) 'textColor': textColor,
      if (promptColor != null) 'promptColor': promptColor,
      if (onCommand != null) 'onCommand': onCommand,
    };
  }

  /// Renders a string. The canonical content field is `text`.
  static Map<String, dynamic> text({
    required String text,
    String? variant,
    dynamic style,
    dynamic dropCap,
    num? maxLines,
    String? overflow,
    String? textAlign,
  }) {
    return <String, dynamic>{
      'type': 'text',
      'text': text,
      if (variant != null) 'variant': variant,
      if (style != null) 'style': style,
      if (dropCap != null) 'dropCap': dropCap,
      if (maxLines != null) 'maxLines': maxLines,
      if (overflow != null) 'overflow': overflow,
      if (textAlign != null) 'textAlign': textAlign,
    };
  }

  /// Single-line (or multi-line when `maxLines > 1`) text entry. Follows the
  /// shared input contract (spec §2.6.0): when `binding` is set, the runtime
  /// reads the current value from the state path and writes user input back
  /// without requiring an explicit `onChange`. Explicit `value` + `onChange`
  /// override the shorthand.
  static Map<String, dynamic> textInput({
    String? binding,
    dynamic value,
    bool? enabled,
    String? label,
    String? placeholder,
    String? helperText,
    String? prefixIcon,
    String? suffixIcon,
    bool? obscureText,
    bool? readOnly,
    int? maxLines,
    int? maxLength,
    String? inputType,
    dynamic validation,
  }) {
    return <String, dynamic>{
      'type': 'textInput',
      if (binding != null) 'binding': binding,
      if (value != null) 'value': value,
      if (enabled != null) 'enabled': enabled,
      if (label != null) 'label': label,
      if (placeholder != null) 'placeholder': placeholder,
      if (helperText != null) 'helperText': helperText,
      if (prefixIcon != null) 'prefixIcon': prefixIcon,
      if (suffixIcon != null) 'suffixIcon': suffixIcon,
      if (obscureText != null) 'obscureText': obscureText,
      if (readOnly != null) 'readOnly': readOnly,
      if (maxLines != null) 'maxLines': maxLines,
      if (maxLength != null) 'maxLength': maxLength,
      if (inputType != null) 'inputType': inputType,
      if (validation != null) 'validation': validation,
    };
  }

  /// Time input. Shared rows per §2.6.0; `value` is a time string (e.g., `"14:30"`).
  static Map<String, dynamic> timeField({
    String? label,
    String? format,
    bool? use24HourFormat,
    String? mode,
  }) {
    return <String, dynamic>{
      'type': 'timeField',
      if (label != null) 'label': label,
      if (format != null) 'format': format,
      if (use24HourFormat != null) 'use24HourFormat': use24HourFormat,
      if (mode != null) 'mode': mode,
    };
  }

  /// Standalone time picker surface. Shared rows per §2.6.0; `value` is a time string.
  static Map<String, dynamic> timePicker({
    bool? use24HourFormat,
  }) {
    return <String, dynamic>{
      'type': 'timePicker',
      if (use24HourFormat != null) 'use24HourFormat': use24HourFormat,
    };
  }

  /// Chronological timeline of events.
  static Map<String, dynamic> timeline({
    required dynamic items,
    required String items___title,
    String? items___subtitle,
    String? items___icon,
    String? items___time,
    String? items___color,
    String? orientation,
  }) {
    return <String, dynamic>{
      'type': 'timeline',
      'items': items,
      'items[].title': items___title,
      if (items___subtitle != null) 'items[].subtitle': items___subtitle,
      if (items___icon != null) 'items[].icon': items___icon,
      if (items___time != null) 'items[].time': items___time,
      if (items___color != null) 'items[].color': items___color,
      if (orientation != null) 'orientation': orientation,
    };
  }

  /// Binary on/off control. Shared `binding` / `value` / `enabled` / `onChange` per §2.6.0; `value` is `boolean`.
  static Map<String, dynamic> toggle() {
    return <String, dynamic>{
      'type': 'toggle',
    };
  }

  /// Wrapper that reveals a tooltip on hover or long-press.
  static Map<String, dynamic> tooltip({
    required String message,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'tooltip',
      'message': message,
      'child': child,
    };
  }

  /// Geometric transformation (rotate, scale, translate) applied to a child.
  static Map<String, dynamic> transform({
    num? rotate,
    dynamic scale,
    dynamic translate,
    dynamic origin,
    bool? animated,
    num? duration,
    String? curve,
    required dynamic child,
  }) {
    return <String, dynamic>{
      'type': 'transform',
      if (rotate != null) 'rotate': rotate,
      if (scale != null) 'scale': scale,
      if (translate != null) 'translate': translate,
      if (origin != null) 'origin': origin,
      if (animated != null) 'animated': animated,
      if (duration != null) 'duration': duration,
      if (curve != null) 'curve': curve,
      'child': child,
    };
  }

  /// Hierarchical tree view with expandable nodes.
  static Map<String, dynamic> tree({
    required dynamic data,
    String? childrenKey,
    num? indentation,
    dynamic itemPadding,
    dynamic itemTemplate,
    bool? expandable,
    bool? initiallyExpanded,
    bool? selectable,
    bool? showLines,
    dynamic selectedColor,
    dynamic lineColor,
    num? width,
    num? height,
    dynamic onNodeTap,
    dynamic onSelect,
    dynamic onExpand,
    dynamic onCollapse,
  }) {
    return <String, dynamic>{
      'type': 'tree',
      'data': data,
      if (childrenKey != null) 'childrenKey': childrenKey,
      if (indentation != null) 'indentation': indentation,
      if (itemPadding != null) 'itemPadding': itemPadding,
      if (itemTemplate != null) 'itemTemplate': itemTemplate,
      if (expandable != null) 'expandable': expandable,
      if (initiallyExpanded != null) 'initiallyExpanded': initiallyExpanded,
      if (selectable != null) 'selectable': selectable,
      if (showLines != null) 'showLines': showLines,
      if (selectedColor != null) 'selectedColor': selectedColor,
      if (lineColor != null) 'lineColor': lineColor,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (onNodeTap != null) 'onNodeTap': onNodeTap,
      if (onSelect != null) 'onSelect': onSelect,
      if (onExpand != null) 'onExpand': onExpand,
      if (onCollapse != null) 'onCollapse': onCollapse,
    };
  }

  /// Instantiates a named template (see §9.6).
  static Map<String, dynamic> use({
    required String template,
    dynamic params,
    dynamic slots,
  }) {
    return <String, dynamic>{
      'type': 'use',
      'template': template,
      if (params != null) 'params': params,
      if (slots != null) 'slots': slots,
    };
  }

  /// Vertical separator, typically used in horizontal layouts.
  static Map<String, dynamic> verticalDivider({
    num? width,
    num? thickness,
    String? color,
    num? indent,
    num? endIndent,
  }) {
    return <String, dynamic>{
      'type': 'verticalDivider',
      if (width != null) 'width': width,
      if (thickness != null) 'thickness': thickness,
      if (color != null) 'color': color,
      if (indent != null) 'indent': indent,
      if (endIndent != null) 'endIndent': endIndent,
    };
  }

  /// Shows or hides a child with optional state preservation and replacement content.
  static Map<String, dynamic> visibility({
    dynamic visible,
    bool? maintainSize,
    bool? maintainState,
    dynamic replacement,
    dynamic child,
    dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'visibility',
      if (visible != null) 'visible': visible,
      if (maintainSize != null) 'maintainSize': maintainSize,
      if (maintainState != null) 'maintainState': maintainState,
      if (replacement != null) 'replacement': replacement,
      if (child != null) 'child': child,
      if (children != null) 'children': children,
    };
  }

  /// Embedded web view.
  static Map<String, dynamic> webView({
    String? url,
    String? html,
    bool? allowNavigation,
    bool? enableJavaScript,
    bool? enableZoom,
    num? width,
    num? height,
    dynamic onPageStarted,
    dynamic onPageFinished,
    dynamic onError,
  }) {
    return <String, dynamic>{
      'type': 'webView',
      if (url != null) 'url': url,
      if (html != null) 'html': html,
      if (allowNavigation != null) 'allowNavigation': allowNavigation,
      if (enableJavaScript != null) 'enableJavaScript': enableJavaScript,
      if (enableZoom != null) 'enableZoom': enableZoom,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (onPageStarted != null) 'onPageStarted': onPageStarted,
      if (onPageFinished != null) 'onPageFinished': onPageFinished,
      if (onError != null) 'onError': onError,
    };
  }

  /// Flow layout that wraps children to the next line when they exceed available width/height.
  static Map<String, dynamic> wrap({
    String? direction,
    num? spacing,
    num? runSpacing,
    String? alignment,
    required dynamic children,
  }) {
    return <String, dynamic>{
      'type': 'wrap',
      if (direction != null) 'direction': direction,
      if (spacing != null) 'spacing': spacing,
      if (runSpacing != null) 'runSpacing': runSpacing,
      if (alignment != null) 'alignment': alignment,
      'children': children,
    };
  }

}
