/// C header generator for MCP UI DSL.
///
/// Emits a single-include `.h` file with a `static inline const char*`
/// function that returns the MCP UI DSL JSON for the supplied
/// definition. Consumers parse the JSON with their own JSON library
/// (cJSON, json-c, etc.).
///
/// Target: C11 / GCC / Clang. No external dependencies.
library;

import 'dart:convert';

class CCodeGenerator {
  /// Generate a complete C header from a full definition.
  ///
  /// Usage:
  /// ```dart
  /// final code = CCodeGenerator.fromDefinition(myAppDef);
  /// // Write `code` to mcp_ui_app.h and #include it from C.
  /// ```
  static String fromDefinition(Map<String, dynamic> definition) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = 'create_${_toSnakeCase(type)}';
    final guard = _guardName(funcName);
    return _emit(guard, funcName, definition,
        comment: 'MCP UI DSL $type definition.');
  }

  /// Generate a C header for an application definition.
  static String fromApplication(Map<String, dynamic> app) {
    return _emit('MCP_UI_APPLICATION_H', 'create_application', app,
        comment: 'MCP UI DSL application definition.');
  }

  /// Generate a C header for a page definition.
  static String fromPage(Map<String, dynamic> page) {
    final title = _sanitizeIdentifier(page['title'] as String? ?? 'page');
    final func = 'create_${title}_page';
    return _emit(_guardName(func), func, page,
        comment: 'MCP UI DSL page definition.');
  }

  /// Generate a C header for a single widget.
  static String fromWidget(Map<String, dynamic> widget) {
    final type = _toSnakeCase(widget['type'] as String? ?? 'widget');
    final func = 'create_$type';
    return _emit(_guardName(func), func, widget,
        comment: 'MCP UI DSL widget.');
  }

  static String _emit(
    String guard,
    String funcName,
    Map<String, dynamic> definition, {
    required String comment,
  }) {
    final json = jsonEncode(definition);
    final sb = StringBuffer()
      ..writeln('/* Code generated by flutter_mcp_ui_generator '
          'CCodeGenerator. DO NOT EDIT. */')
      ..writeln('/* Regenerate from source using the Dart generator. */')
      ..writeln()
      ..writeln('#ifndef $guard')
      ..writeln('#define $guard')
      ..writeln()
      ..writeln('/* $comment */')
      ..writeln('static inline const char* $funcName(void) {')
      ..writeln('    return ${_cStringLiteral(json)};')
      ..writeln('}')
      ..writeln()
      ..writeln('#endif /* $guard */')
      ..writeln();
    return sb.toString();
  }

  /// Encode a JSON string as a C string literal. Long inputs are split
  /// across multiple adjacent string-literal lines (C concatenates
  /// adjacent string literals at compile time) so the generated header
  /// reads sensibly in an editor without violating any pre-C99 line
  /// length limits.
  static String _cStringLiteral(String s) {
    const chunkSize = 200;
    final escaped = StringBuffer();
    for (final r in s.runes) {
      escaped.write(_escapeC(r));
    }
    final esc = escaped.toString();
    if (esc.length <= chunkSize) return '"$esc"';
    final parts = <String>[];
    for (var i = 0; i < esc.length; i += chunkSize) {
      final end = (i + chunkSize) > esc.length ? esc.length : i + chunkSize;
      var slice = esc.substring(i, end);
      // Avoid splitting an escape sequence in half.
      while (slice.endsWith(r'\') && end < esc.length) {
        slice = esc.substring(i, end + 1);
        i++;
      }
      parts.add('"$slice"');
    }
    return parts.join('\n        ');
  }

  static String _escapeC(int r) {
    switch (r) {
      case 0x08:
        return r'\b';
      case 0x09:
        return r'\t';
      case 0x0A:
        return r'\n';
      case 0x0B:
        return r'\v';
      case 0x0C:
        return r'\f';
      case 0x0D:
        return r'\r';
      case 0x22:
        return r'\"';
      case 0x5C:
        return r'\\';
    }
    if (r < 0x20 || r == 0x7F) {
      return '\\x${r.toRadixString(16).padLeft(2, '0').toUpperCase()}';
    }
    if (r > 0x7F) {
      // UTF-8 byte stream — emit as the original byte sequence so the
      // resulting `const char*` carries valid UTF-8 at runtime.
      final bytes = utf8.encode(String.fromCharCode(r));
      return bytes
          .map((b) =>
              '\\x${b.toRadixString(16).padLeft(2, '0').toUpperCase()}')
          .join();
    }
    return String.fromCharCode(r);
  }

  static String _toSnakeCase(String s) =>
      s.replaceAllMapped(RegExp(r'[A-Z]'), (m) => '_${m[0]!.toLowerCase()}')
          .replaceAll(RegExp(r'^_'), '')
          .replaceAll(RegExp(r'[\s\-\.]'), '_');

  static String _sanitizeIdentifier(String s) {
    final c = s.replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_').toLowerCase();
    return c.isEmpty || RegExp(r'^[0-9]').hasMatch(c) ? '_$c' : c;
  }

  static String _guardName(String func) =>
      'MCP_UI_${func.toUpperCase().replaceAll('-', '_')}_H';
}
