/// C++ header generator for MCP UI DSL.
///
/// Emits a single-include `.hpp` file with an `inline std::string`
/// function that returns the MCP UI DSL JSON for the supplied
/// definition. Uses C++11 raw string literals so the JSON survives
/// without escape juggling.
///
/// Target: C++11 or later. Only depends on `<string>`.
library;

import 'dart:convert';

class CppCodeGenerator {
  /// Generate a complete C++ header from a full definition.
  ///
  /// Usage:
  /// ```dart
  /// final code = CppCodeGenerator.fromDefinition(myAppDef);
  /// // Write `code` to mcp_ui_app.hpp and #include from C++.
  /// ```
  static String fromDefinition(
    Map<String, dynamic> definition, {
    String namespace = 'mcp_ui',
  }) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = 'create_${_toSnakeCase(type)}';
    return _emit(funcName, definition, namespace: namespace,
        comment: 'MCP UI DSL $type definition.');
  }

  /// Generate a C++ header for an application definition.
  static String fromApplication(
    Map<String, dynamic> app, {
    String namespace = 'mcp_ui',
  }) {
    return _emit('create_application', app, namespace: namespace,
        comment: 'MCP UI DSL application definition.');
  }

  /// Generate a C++ header for a page definition.
  static String fromPage(
    Map<String, dynamic> page, {
    String namespace = 'mcp_ui',
  }) {
    final title = _sanitizeIdentifier(page['title'] as String? ?? 'page');
    return _emit('create_${title}_page', page, namespace: namespace,
        comment: 'MCP UI DSL page definition.');
  }

  /// Generate a C++ header for a single widget.
  static String fromWidget(
    Map<String, dynamic> widget, {
    String namespace = 'mcp_ui',
  }) {
    final type = _toSnakeCase(widget['type'] as String? ?? 'widget');
    return _emit('create_$type', widget, namespace: namespace,
        comment: 'MCP UI DSL widget.');
  }

  static String _emit(
    String funcName,
    Map<String, dynamic> definition, {
    required String namespace,
    required String comment,
  }) {
    final json = jsonEncode(definition);
    final delimiter = _safeDelimiter(json);
    final sb = StringBuffer()
      ..writeln('// Code generated by flutter_mcp_ui_generator '
          'CppCodeGenerator. DO NOT EDIT.')
      ..writeln('// Regenerate from source using the Dart generator.')
      ..writeln()
      ..writeln('#pragma once')
      ..writeln()
      ..writeln('#include <string>')
      ..writeln();
    if (namespace.isNotEmpty) {
      sb.writeln('namespace $namespace {');
      sb.writeln();
    }
    sb
      ..writeln('// $comment')
      ..writeln('inline std::string $funcName() {')
      ..writeln('    return R"$delimiter($json)$delimiter";')
      ..writeln('}')
      ..writeln();
    if (namespace.isNotEmpty) {
      sb.writeln('}  // namespace $namespace');
      sb.writeln();
    }
    return sb.toString();
  }

  /// Pick a raw-string delimiter that does not occur in the payload.
  /// `R"<delim>(...)<delim>"` — if the JSON ever contains the literal
  /// `)<delim>"` the delimiter must change. C++11 allows up to 16
  /// printable characters (no spaces, parens, backslashes).
  static String _safeDelimiter(String payload) {
    const candidates = ['json', 'mcpui', 'dsl', 'r1', 'r2', 'guard'];
    for (final c in candidates) {
      if (!payload.contains(')$c"')) return c;
    }
    return 'mcp_ui_unique_${DateTime.now().microsecondsSinceEpoch}';
  }

  static String _toSnakeCase(String s) =>
      s.replaceAllMapped(RegExp(r'[A-Z]'), (m) => '_${m[0]!.toLowerCase()}')
          .replaceAll(RegExp(r'^_'), '')
          .replaceAll(RegExp(r'[\s\-\.]'), '_');

  static String _sanitizeIdentifier(String s) {
    final c = s.replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_').toLowerCase();
    return c.isEmpty || RegExp(r'^[0-9]').hasMatch(c) ? '_$c' : c;
  }
}
