/// Dart code generator for MCP UI DSL
///
/// Emits Dart source that returns a `Map<String, dynamic>` matching the
/// supplied MCP UI DSL JSON definition. Mirrors the Python / JS / TS /
/// Go / C generators (spec §5.3 Multi-Language Code Generation) so a
/// definition authored once can be embedded as a Dart `const`-style
/// builder in any host (vibe `inline` server target, headless CLI
/// servers, hand-rolled apps).
library;

import 'dart:convert';

/// Generates Dart source code that returns the MCP UI DSL JSON as a
/// `Map<String, dynamic>`.
///
/// Usage:
/// ```dart
/// final code = DartCodeGenerator.fromDefinition(myAppDef);
/// // Write `code` to lib/generated/ui_definition.dart and import the
/// // resulting `createApplication()` function from your MCP server.
/// ```
class DartCodeGenerator {
  /// Generate a complete Dart library from a full definition.
  /// Produces a `create<Type>()` function returning `Map<String,dynamic>`.
  static String fromDefinition(Map<String, dynamic> definition) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = 'create${_toPascalCase(type)}';
    return _generateFunction(funcName, definition,
        docComment: 'Generated MCP UI DSL $type definition.');
  }

  /// Generate a Dart function for an application definition.
  static String fromApplication(Map<String, dynamic> app) {
    return _generateFunction('createApplication', app,
        docComment: 'Generated MCP UI DSL application definition.');
  }

  /// Generate a Dart function for a page definition. Uses the page
  /// title (sanitised) so a project with several pages produces
  /// distinct function names — `createHomePage()`, `createSettingsPage()`.
  static String fromPage(Map<String, dynamic> page) {
    final title =
        _toPascalCase(page['title'] as String? ?? page['id'] as String? ?? 'page');
    return _generateFunction('create${title}Page', page,
        docComment: 'Generated MCP UI DSL page definition.');
  }

  /// Generate a Dart function for a single widget.
  static String fromWidget(Map<String, dynamic> widget) {
    final type = widget['type'] as String? ?? 'widget';
    return _generateFunction('create${_toPascalCase(type)}', widget,
        docComment: 'Generated MCP UI DSL widget.');
  }

  /// Convert a definition into a Dart helper library with a `build()`
  /// function plus a top-level `kModuleName` const — matches the
  /// other generators' `toModule` shape so callers can pick uniform
  /// emit verbs across languages.
  static String toModule(
    String moduleName,
    Map<String, dynamic> definition,
  ) {
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('const String kModuleName = ${_dartString(moduleName)};');
    sb.writeln();
    sb.writeln('/// Return the MCP UI DSL definition map.');
    sb.writeln('Map<String, dynamic> build() {');
    sb.writeln('  return ${_toDartLiteral(definition, indent: 1)};');
    sb.writeln('}');
    return sb.toString();
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _header() => '''// Auto-generated MCP UI DSL definition.
// Generated by flutter_mcp_ui_generator DartCodeGenerator.
// Do not edit manually — regenerate from source instead.
// ignore_for_file: prefer_single_quotes, always_specify_types,
// require_trailing_commas, lines_longer_than_80_chars,
// prefer_const_literals_to_create_immutables,
// prefer_const_constructors

''';

  static String _generateFunction(
    String funcName,
    Map<String, dynamic> definition, {
    String? docComment,
  }) {
    final sb = StringBuffer();
    sb.writeln(_header());
    if (docComment != null) {
      sb.writeln('/// $docComment');
    }
    sb.writeln('Map<String, dynamic> $funcName() {');
    sb.writeln('  return ${_toDartLiteral(definition, indent: 1)};');
    sb.writeln('}');
    return sb.toString();
  }

  /// Convert a JSON-decoded value into a Dart literal string with the
  /// given indentation. Mirrors the Python generator's `_toPythonLiteral`
  /// shape so output stays diff-friendly across languages.
  static String _toDartLiteral(dynamic value, {int indent = 0}) {
    final pad = '  ' * indent;
    final padInner = '  ' * (indent + 1);

    if (value == null) return 'null';
    if (value is bool) return value ? 'true' : 'false';
    if (value is num) {
      // Whole numbers stay as ints, fractional as doubles. Avoid
      // `42.0` for what was an int in JSON to keep emit minimal.
      if (value is int) return value.toString();
      if (value == value.truncateToDouble() &&
          value.abs() < 1e16) {
        return '${value.toInt()}';
      }
      return value.toString();
    }
    if (value is String) return _dartString(value);

    if (value is List) {
      if (value.isEmpty) return '<dynamic>[]';
      final items = value
          .map((e) => '$padInner${_toDartLiteral(e, indent: indent + 1)}')
          .join(',\n');
      return '<dynamic>[\n$items,\n$pad]';
    }

    if (value is Map) {
      if (value.isEmpty) return '<String, dynamic>{}';
      final entries = value.entries
          .map((e) =>
              '$padInner${_dartString(e.key.toString())}: ${_toDartLiteral(e.value, indent: indent + 1)}')
          .join(',\n');
      return '<String, dynamic>{\n$entries,\n$pad}';
    }

    // Fallback: JSON-encode unknown values and embed as a string.
    return _dartString(jsonEncode(value));
  }

  /// Emit a Dart string literal — escapes the canonical set
  /// (`\`, `'`, `$`, control chars). Single-quoted to match the
  /// majority of Dart linters' default; consumer styleguide rules
  /// can rewrite if they prefer double.
  static String _dartString(String s) {
    final escaped = s
        .replaceAll('\\', r'\\')
        .replaceAll('\$', r'\$')
        .replaceAll("'", r"\'")
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
    return "'$escaped'";
  }

  static String _toPascalCase(String s) {
    if (s.isEmpty) return 'X';
    final cleaned = s.replaceAll(RegExp(r'[^A-Za-z0-9]'), ' ');
    final parts = cleaned.split(RegExp(r'\s+')).where((p) => p.isNotEmpty);
    final pascal = parts
        .map((p) => p[0].toUpperCase() + p.substring(1).toLowerCase())
        .join();
    if (pascal.isEmpty) return 'X';
    // Dart identifiers can't start with a digit.
    if (RegExp(r'^[0-9]').hasMatch(pascal)) return 'X$pascal';
    return pascal;
  }
}
