/// Go code generator for MCP UI DSL
///
/// Generates Go functions that produce MCP UI DSL JSON via map literals.
/// Target: Go function generating UI struct/map (spec §5.3 Multi-Language Code Generation)
library;

import 'dart:convert';

/// Generates Go source code that produces MCP UI DSL JSON.
///
/// Usage:
/// ```dart
/// final code = GoCodeGenerator.fromDefinition(myAppDef, package: 'main');
/// // Write code to a .go file for use in a Go MCP server
/// ```
class GoCodeGenerator {
  /// Generate a complete Go file from a full definition.
  static String fromDefinition(
    Map<String, dynamic> definition, {
    String package = 'mcpui',
  }) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = 'Create${_toPascalCase(type)}';
    final sb = StringBuffer();
    sb.writeln(_header(package));
    sb.writeln('// $funcName returns the MCP UI DSL $type definition.');
    sb.writeln('func $funcName() map[string]interface{} {');
    sb.writeln('\treturn ${_toGoLiteral(definition, indent: 1)}');
    sb.writeln('}');
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Generate Go for an application definition.
  /// Uses `package main` with `func main()` since applications are executables.
  static String fromApplication(
    Map<String, dynamic> app, {
    String package = 'main',
  }) =>
      _generateFunc('CreateApplication', app, package: package,
          comment: 'CreateApplication returns a generated MCP UI DSL application definition.',
          includeMain: true);

  /// Generate Go for a page definition.
  /// Uses `package mcpui` (library, not executable) without `func main()`.
  static String fromPage(
    Map<String, dynamic> page, {
    String package = 'mcpui',
  }) {
    final title = _toPascalCase(page['title'] as String? ?? 'page');
    return _generateFunc('Create${title}Page', page, package: package,
        comment: 'Create${title}Page returns a generated MCP UI DSL page definition.',
        includeMain: false);
  }

  /// Generate Go for a single widget.
  /// Uses `package mcpui` (library, not executable) without `func main()`.
  static String fromWidget(
    Map<String, dynamic> widget, {
    String package = 'mcpui',
  }) {
    final type = _toPascalCase(widget['type'] as String? ?? 'widget');
    return _generateFunc('Create$type', widget, package: package,
        comment: 'Create$type returns a generated MCP UI DSL widget.',
        includeMain: false);
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _header(String package, {bool includeImports = true}) {
    final sb = StringBuffer();
    sb.writeln('// Code generated by flutter_mcp_ui_generator GoCodeGenerator. DO NOT EDIT.');
    sb.writeln('// Regenerate from source using the Dart generator.');
    sb.writeln();
    sb.writeln('package $package');
    if (includeImports) {
      sb.writeln();
      sb.writeln('import (');
      sb.writeln('\t"encoding/json"');
      sb.writeln('\t"fmt"');
      sb.writeln(')');
    }
    sb.writeln();
    return sb.toString();
  }

  static String _mainBlock(String funcName) => '''func main() {
\tdef := $funcName()
\tb, err := json.MarshalIndent(def, "", "  ")
\tif err != nil {
\t\tpanic(err)
\t}
\tfmt.Println(string(b))
}
''';

  static String _generateFunc(
    String funcName,
    Map<String, dynamic> definition, {
    required String package,
    String? comment,
    bool includeMain = true,
  }) {
    final sb = StringBuffer();
    sb.writeln(_header(package, includeImports: includeMain));
    if (comment != null) {
      sb.writeln('// $comment');
    }
    sb.writeln('func $funcName() map[string]interface{} {');
    sb.writeln('\treturn ${_toGoLiteral(definition, indent: 1)}');
    sb.writeln('}');
    sb.writeln();
    if (includeMain) {
      sb.writeln(_mainBlock(funcName));
    }
    return sb.toString();
  }

  /// Convert a Dart value to a Go map literal string
  static String _toGoLiteral(dynamic value, {int indent = 0}) {
    final tab = '\t' * indent;
    final tabInner = '\t' * (indent + 1);

    if (value == null) return 'nil';
    if (value is bool) return value ? 'true' : 'false';
    if (value is int) return value.toString();
    if (value is double) return value.toString();
    if (value is num) return value.toString();
    if (value is String) return '"${_escapeGo(value)}"';

    if (value is List) {
      if (value.isEmpty) return '[]interface{}{}';
      final items = value
          .map((e) => '$tabInner${_toGoLiteral(e, indent: indent + 1)},')
          .join('\n');
      return '[]interface{}{\n$items\n$tab}';
    }

    if (value is Map) {
      if (value.isEmpty) return 'map[string]interface{}{}';
      final entries = value.entries
          .map((e) =>
              '$tabInner"${_escapeGo(e.key.toString())}": ${_toGoLiteral(e.value, indent: indent + 1)},')
          .join('\n');
      return 'map[string]interface{}{\n$entries\n$tab}';
    }

    return '"${_escapeGo(jsonEncode(value))}"';
  }

  static String _escapeGo(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n');

  static String _toPascalCase(String s) {
    return s
        .split(RegExp(r'[_\s\-\.]'))
        .map((p) => p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1))
        .join();
  }
}
