/// JavaScript code generator for MCP UI DSL
///
/// Generates JavaScript (ES module) functions that produce MCP UI DSL JSON objects.
/// Target: JavaScript function generating UI object (spec §5.3 Multi-Language Code Generation)
library;

import 'dart:convert';

/// Generates JavaScript (ESM) source code that produces MCP UI DSL JSON.
///
/// Usage:
/// ```dart
/// final code = JavaScriptCodeGenerator.fromDefinition(myAppDef);
/// // Write code to a .mjs file for use in a Node.js MCP server
/// ```
class JavaScriptCodeGenerator {
  /// Generate a complete JavaScript module from a full definition.
  static String fromDefinition(Map<String, dynamic> definition) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = _toCamelCase('create_$type');
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('export function $funcName() {');
    sb.writeln('  return ${_toJsLiteral(definition, indent: 1)};');
    sb.writeln('}');
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Generate JavaScript for an application definition.
  static String fromApplication(Map<String, dynamic> app) =>
      _generateFunction('createApplication', app,
          docstring: 'Generated MCP UI DSL application definition.');

  /// Generate JavaScript for a page definition.
  static String fromPage(Map<String, dynamic> page) {
    final title = _sanitizeIdentifier(page['title'] as String? ?? 'page');
    return _generateFunction('create${_capitalize(title)}Page', page,
        docstring: 'Generated MCP UI DSL page definition.');
  }

  /// Generate JavaScript for a single widget.
  static String fromWidget(Map<String, dynamic> widget) {
    final type =
        _capitalize(_toCamelCase(widget['type'] as String? ?? 'widget'));
    return _generateFunction('create$type', widget,
        docstring: 'Generated MCP UI DSL widget.');
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _header() => '''// Auto-generated MCP UI DSL definition.
// Generated by flutter_mcp_ui_generator JavaScriptCodeGenerator.
// Do not edit manually — regenerate from source instead.
// @ts-check
''';

  static String _mainBlock(String funcName) => '''// Run with: node <file>.mjs
if (process.argv[1] === new URL(import.meta.url).pathname) {
  console.log(JSON.stringify($funcName(), null, 2));
}
''';

  static String _generateFunction(
    String funcName,
    Map<String, dynamic> definition, {
    String? docstring,
  }) {
    final sb = StringBuffer();
    sb.writeln(_header());
    if (docstring != null) {
      sb.writeln('/** $docstring */');
    }
    sb.writeln('export function $funcName() {');
    sb.writeln('  return ${_toJsLiteral(definition, indent: 1)};');
    sb.writeln('}');
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Convert a Dart value to a JavaScript object literal string
  static String _toJsLiteral(dynamic value, {int indent = 0}) {
    final pad = '  ' * indent;
    final padInner = '  ' * (indent + 1);

    if (value == null) return 'null';
    if (value is bool) return value ? 'true' : 'false';
    if (value is num) return value.toString();
    if (value is String) return "'${_escapeJs(value)}'";

    if (value is List) {
      if (value.isEmpty) return '[]';
      final items = value
          .map((e) => '$padInner${_toJsLiteral(e, indent: indent + 1)}')
          .join(',\n');
      return '[\n$items,\n$pad]';
    }

    if (value is Map) {
      if (value.isEmpty) return '{}';
      final entries = value.entries
          .map((e) =>
              '$padInner${_jsKey(e.key.toString())}: ${_toJsLiteral(e.value, indent: indent + 1)}')
          .join(',\n');
      return '{\n$entries,\n$pad}';
    }

    return "'${_escapeJs(jsonEncode(value))}'";
  }

  static String _jsKey(String key) =>
      RegExp(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$').hasMatch(key) ? key : "'$key'";

  static String _escapeJs(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n');

  static String _toCamelCase(String s) {
    final parts = s.split(RegExp(r'[_\s\-]'));
    return parts.first +
        parts.skip(1).map((p) => _capitalize(p)).join();
  }

  static String _capitalize(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

  static String _sanitizeIdentifier(String s) =>
      s.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
}
