/// Python code generator for MCP UI DSL
///
/// Generates Python functions that produce MCP UI DSL JSON dicts.
/// Target: Python function generating UI dict (spec §5.3 Multi-Language Code Generation)
library;

import 'dart:convert';

/// Generates Python source code that produces MCP UI DSL JSON.
///
/// Usage:
/// ```dart
/// final code = PythonCodeGenerator.fromDefinition(myAppDef);
/// // Write code to a .py file for use in a Python MCP server
/// ```
class PythonCodeGenerator {
  /// Generate a complete Python module from a full application definition.
  ///
  /// Produces a `create_application()` function plus a `main()` block
  /// that prints the JSON output.
  static String fromDefinition(Map<String, dynamic> definition) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = _toSnakeCase(type);
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('def create_$funcName():');
    sb.writeln('    """Generated MCP UI DSL $type definition."""');
    sb.writeln('    return ${_toPythonLiteral(definition, indent: 1)}');
    sb.writeln();
    sb.writeln();
    sb.writeln(_mainBlock('create_$funcName'));
    return sb.toString();
  }

  /// Generate a Python function for an application definition.
  static String fromApplication(Map<String, dynamic> app) {
    return _generateFunction('create_application', app,
        docstring: 'Generated MCP UI DSL application definition.');
  }

  /// Generate a Python function for a page definition.
  static String fromPage(Map<String, dynamic> page) {
    final title = _sanitizeIdentifier(page['title'] as String? ?? 'page');
    return _generateFunction('create_${title}_page', page,
        docstring: 'Generated MCP UI DSL page definition.');
  }

  /// Generate a Python function for a single widget.
  static String fromWidget(Map<String, dynamic> widget) {
    final type = _toSnakeCase(widget['type'] as String? ?? 'widget');
    return _generateFunction('create_$type', widget,
        docstring: 'Generated MCP UI DSL widget.');
  }

  /// Convert a Dart Map to a Python-compatible JSON helper module.
  ///
  /// Returns a Python source file with a `build()` function and `__main__` block.
  static String toModule(
    String moduleName,
    Map<String, dynamic> definition,
  ) {
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('MODULE_NAME = "${_escapePy(moduleName)}"');
    sb.writeln();
    sb.writeln('def build():');
    sb.writeln('    """Return the MCP UI DSL definition dict."""');
    sb.writeln('    return ${_toPythonLiteral(definition, indent: 1)}');
    sb.writeln();
    sb.writeln();
    sb.writeln(_mainBlock('build'));
    return sb.toString();
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _header() => '''#!/usr/bin/env python3
"""Auto-generated MCP UI DSL definition.
Generated by flutter_mcp_ui_generator PythonCodeGenerator.
Do not edit manually — regenerate from source instead.
"""
import json
''';

  static String _mainBlock(String funcName) => '''if __name__ == "__main__":
    print(json.dumps($funcName(), indent=2))
''';

  static String _generateFunction(
    String funcName,
    Map<String, dynamic> definition, {
    String? docstring,
  }) {
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('def $funcName():');
    if (docstring != null) {
      sb.writeln('    """$docstring"""');
    }
    sb.writeln('    return ${_toPythonLiteral(definition, indent: 1)}');
    sb.writeln();
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Convert a Dart value to a Python literal string
  static String _toPythonLiteral(dynamic value, {int indent = 0}) {
    final pad = '    ' * indent;
    final padInner = '    ' * (indent + 1);

    if (value == null) return 'None';
    if (value is bool) return value ? 'True' : 'False';
    if (value is num) return value.toString();
    if (value is String) return '"${_escapePy(value)}"';

    if (value is List) {
      if (value.isEmpty) return '[]';
      final items = value
          .map((e) => '$padInner${_toPythonLiteral(e, indent: indent + 1)}')
          .join(',\n');
      return '[\n$items,\n$pad]';
    }

    if (value is Map) {
      if (value.isEmpty) return '{}';
      final entries = value.entries
          .map((e) =>
              '$padInner"${_escapePy(e.key.toString())}": ${_toPythonLiteral(e.value, indent: indent + 1)}')
          .join(',\n');
      return '{\n$entries,\n$pad}';
    }

    // Fallback: JSON encode and wrap
    return '"${_escapePy(jsonEncode(value))}"';
  }

  static String _escapePy(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n');

  static String _toSnakeCase(String s) => s
      .replaceAllMapped(RegExp(r'([A-Z])'), (m) => '_${m.group(0)!.toLowerCase()}')
      .replaceAll(RegExp(r'^_'), '')
      .replaceAll(RegExp(r'[^a-z0-9_]'), '_');

  static String _sanitizeIdentifier(String s) =>
      s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_');
}
