/// TypeScript code generator for MCP UI DSL
///
/// Generates TypeScript functions that produce MCP UI DSL JSON objects.
/// Target: TypeScript function generating UI object (spec §5.3 Multi-Language Code Generation)
library;

import 'dart:convert';

/// Generates TypeScript source code that produces MCP UI DSL JSON.
///
/// Usage:
/// ```dart
/// final code = TypeScriptCodeGenerator.fromDefinition(myAppDef);
/// // Write code to a .ts file for use in a TypeScript MCP server
/// ```
class TypeScriptCodeGenerator {
  /// Generate a complete TypeScript module from a full definition.
  static String fromDefinition(Map<String, dynamic> definition) {
    final type = definition['type'] as String? ?? 'unknown';
    final funcName = _toCamelCase('create_$type');
    final sb = StringBuffer();
    sb.writeln(_header());
    sb.writeln('export function $funcName(): MCPUIDefinition {');
    sb.writeln('  return ${_toTsLiteral(definition, indent: 1)};');
    sb.writeln('}');
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Generate TypeScript for an application definition.
  static String fromApplication(Map<String, dynamic> app) =>
      _generateFunction('createApplication', app,
          docstring: 'Generated MCP UI DSL application definition.');

  /// Generate TypeScript for a page definition.
  static String fromPage(Map<String, dynamic> page) {
    final title = _sanitizeIdentifier(page['title'] as String? ?? 'page');
    return _generateFunction('create${_capitalize(title)}Page', page,
        docstring: 'Generated MCP UI DSL page definition.');
  }

  /// Generate TypeScript for a single widget.
  static String fromWidget(Map<String, dynamic> widget) {
    final type = _capitalize(_toCamelCase(widget['type'] as String? ?? 'widget'));
    return _generateFunction('create$type', widget,
        docstring: 'Generated MCP UI DSL widget.');
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _header() => '''// Auto-generated MCP UI DSL definition.
// Generated by flutter_mcp_ui_generator TypeScriptCodeGenerator.
// Do not edit manually — regenerate from source instead.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type MCPUIDefinition = Record<string, any>;
''';

  static String _mainBlock(String funcName) => '''// Run with: npx ts-node <file>.ts
if (require.main === module) {
  console.log(JSON.stringify($funcName(), null, 2));
}
''';

  static String _generateFunction(
    String funcName,
    Map<String, dynamic> definition, {
    String? docstring,
  }) {
    final sb = StringBuffer();
    sb.writeln(_header());
    if (docstring != null) {
      sb.writeln('/** $docstring */');
    }
    sb.writeln('export function $funcName(): MCPUIDefinition {');
    sb.writeln('  return ${_toTsLiteral(definition, indent: 1)};');
    sb.writeln('}');
    sb.writeln();
    sb.writeln(_mainBlock(funcName));
    return sb.toString();
  }

  /// Convert a Dart value to a TypeScript object literal string
  static String _toTsLiteral(dynamic value, {int indent = 0}) {
    final pad = '  ' * indent;
    final padInner = '  ' * (indent + 1);

    if (value == null) return 'null';
    if (value is bool) return value ? 'true' : 'false';
    if (value is num) return value.toString();
    if (value is String) return '`${_escapeTemplate(value)}`';

    if (value is List) {
      if (value.isEmpty) return '[]';
      final items = value
          .map((e) => '$padInner${_toTsLiteral(e, indent: indent + 1)}')
          .join(',\n');
      return '[\n$items,\n$pad]';
    }

    if (value is Map) {
      if (value.isEmpty) return '{}';
      final entries = value.entries
          .map((e) =>
              '$padInner${_tsKey(e.key.toString())}: ${_toTsLiteral(e.value, indent: indent + 1)}')
          .join(',\n');
      return '{\n$entries,\n$pad}';
    }

    return '`${_escapeTemplate(jsonEncode(value))}`';
  }

  /// Quote a key with quotes only if it contains non-identifier characters
  static String _tsKey(String key) =>
      RegExp(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$').hasMatch(key) ? key : '"$key"';

  static String _escapeTemplate(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('\$', '\\\$');

  static String _toCamelCase(String s) {
    final parts = s.split(RegExp(r'[_\s\-]'));
    return parts.first +
        parts.skip(1).map((p) => _capitalize(p)).join();
  }

  static String _capitalize(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

  static String _sanitizeIdentifier(String s) =>
      s.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
}
